Introduce make check-generate
gardener/etcd-druid pull request #177
Opened 2021-05-20 16:12 UTC by timuthy

**How to categorize this PR?**

/area dev-productivity
/area robustness
/kind enhancement
/priority normal

**What this PR does / why we need it**:
A new make target `make check-generate` has been added. Like other for other Gardener projects, the target checks if generation and re-vendoring happened correctly. After merging this PR, the check is executed by the pipeline and will prevent cases as experienced in https://github.com/gardener/etcd-druid/issues/171#issuecomment-844046045.

**Special notes for your reviewer**:
For performance reasons, the `install-requirements` target has been removed as a dependency from other targets and thus must be called explicitly whenever required.

**Release note**:

```other developer
A new Make target `check-generate` has been added to check if generated code and the vendor dir are up-to-date.
```

2021-05-20 18:11 UTC, amshuman-kr requested changes
Thanks for the automated check for the generated files and vendoring! Some small changes below.

Also, `make check-generate` failed for me locally.
```
> Generate / Vendor Check
>> make generate
>> make revendor
make revendor needs to be run:
 M vendor/github.com/gardener/gardener/hack/check.sh
make: *** [check-generate] Error 1
```

2021-05-20 18:11 UTC, amshuman-kr commented on Makefile
> +	@$(REPO_ROOT)/hack/update-codegen.sh
```suggestion
	@"$(REPO_ROOT)/hack/update-codegen.sh"
```

2021-05-20 18:11 UTC, amshuman-kr commented on Makefile
> +	@$(REPO_ROOT)/vendor/github.com/gardener/gardener/hack/check-generate.sh $(REPO_ROOT)
```suggestion
	@"$(REPO_ROOT)/vendor/github.com/gardener/gardener/hack/check-generate.sh" "$(REPO_ROOT)"
```

2021-05-20 18:11 UTC, amshuman-kr commented on Makefile
> +	@$(REPO_ROOT)/vendor/github.com/gardener/gardener/hack/clean.sh ./api/... ./controllers/... ./pkg/...
```suggestion
	@"$(REPO_ROOT)/vendor/github.com/gardener/gardener/hack/clean.sh" ./api/... ./controllers/... ./pkg/...
```

2021-05-21 07:12 UTC, timuthy commented
> Thanks for the automated check for the generated files and vendoring! Some small changes below.
> 
> Also, `make check-generate` failed for me locally.
> 
> ```
> > Generate / Vendor Check
> >> make generate
> >> make revendor
> make revendor needs to be run:
>  M vendor/github.com/gardener/gardener/hack/check.sh
> make: *** [check-generate] Error 1
> ```

Thanks for testing @amshuman-kr. I rebases the PR and now the mentioned error should be gone. Can you please check again?

2021-05-21 14:28 UTC, amshuman-kr requested changes
Thanks a lot @timuthy for rebasing as well as the fix for the flaky test 🚀 

One small change and it is good to merge.

2021-05-21 14:28 UTC, amshuman-kr commented on hack/update-codegen.sh
> +cd "$PROJECT_DIR/api" && controller-gen object:headerFile=$SCRIPT_DIR/boilerplate.go.txt paths=./...
```suggestion
cd "$PROJECT_DIR/api" && controller-gen "object:headerFile=$SCRIPT_DIR/boilerplate.go.txt" paths=./...
```

2021-05-25 06:24 UTC, timuthy commented
Thanks for your review @amshuman-kr. PTAL :)

2021-05-25 06:39 UTC, amshuman-kr approved these changes
/lgtm

2021-05-25 06:40 UTC, merged