[WIP] Integration tests
gardener/etcd-druid pull request #195
Opened 2021-06-21 08:45 UTC by shreyas-s-rao

Signed-off-by: Shreyas Rao <shreyas.sriganesh.rao@sap.com>

**How to categorize this PR?**
/area testing
/kind quality

**What this PR does / why we need it**:
This PR adds cluster-based integration tests for druid.

**Which issue(s) this PR fixes**:
Fixes #

**Special notes for your reviewer**:

**Release note**:

```other developer
Add integration tests.
```

2021-06-29 07:34 UTC, shreyas-s-rao commented
@amshuman-kr @abdasgupta PR is ready for review. I will be adding TM support in a separate PR, once https://github.com/gardener/etcd-backup-restore/pull/348 is tested and merged, since the TM integration aspect is similar for both repos.

2021-07-16 11:48 UTC, shreyas-s-rao commented
/hold till the changes introduced in https://github.com/gardener/etcd-druid/pull/202 related to the operation annotation are accounted for in these tests.

2021-08-31 18:04 UTC, afritzler commented
Any update on this PR? Would be great to have the helm chart for druid.

2022-01-17 16:43 UTC, timuthy requested changes
Thanks @shreyas-s-rao. As discussed offline, can you please remove the TM/pipeline changes? I will file a follow up PR.

2022-01-17 16:43 UTC, timuthy commented on charts/druid/templates/druid-clusterrole.yaml
> +---
Can you please also add permission for `PodDisruptionBudget`? (https://github.com/gardener/etcd-druid/pull/250)

2022-01-17 16:43 UTC, timuthy commented on charts/druid/values.yaml
> +version: v0.6.0-dev-a47e74fd1756951720f8f309cfa34060c677c021
Can you remove this default value? I don't think we should have a dev version in Helm chart we offer.

2022-01-17 16:43 UTC, timuthy commented on charts/druid/values.yaml
> +replicas: 0
```suggestion
replicas: 1
```

2022-01-19 14:31 UTC, timuthy commented on charts/druid/templates/druid-clusterrole.yaml
> +---
In addition, Druid needs the following permissions:
- list/watch/get all `Lease`s
- get/list/watch/create/patch/update `Job`s
- get/list/watch/update/patch `etcdcopybackupstasks`
- get/create/update/patch `etcdcopybackupstasks/status`

2022-02-15 14:48 UTC, timuthy commented
As discussed, this PR is replaced by #296.

/close

2022-02-15 14:49 UTC, closed without merging