Updated label in cronjob job spec to allow it to be uniquely identifi…
gardener/etcd-druid pull request #227
Opened 2021-08-30 14:23 UTC by aaronfern

**How to categorize this PR?**

/area backup
/kind bug

**What this PR does / why we need it**:
Updated label in cronjob job template spec so that it can be identified

**Which issue(s) this PR fixes**:
Fixes #

**Special notes for your reviewer**:

**Release note**:

```other operator
NONE
```

2021-08-31 05:22 UTC, amshuman-kr requested changes
Thanks for the quick change @aaronfern! Looks good. Just a couple of pedantic suggestions 🙂

2021-08-31 05:22 UTC, amshuman-kr commented on charts/etcd/templates/etcd-compaction-cronjob.yaml
> +  schedule: "{{ .Values.backup.backupCompactionSchedule }}"
```suggestion
  schedule: {{ .Values.backup.backupCompactionSchedule | quote }} 
```

2021-08-31 05:22 UTC, amshuman-kr commented on charts/etcd/templates/etcd-compaction-cronjob.yaml
> +            name: etcd-compaction-cronjob
```suggestion
            name: etcd-backup-compaction
```
Let's use the `name` label to indicate what process is actually running in the pod. Technically, it is not a cronjob, just a pod. Pedantic, I know, but still 😅

2021-08-31 05:45 UTC, amshuman-kr approved these changes
LGTM!

2021-11-05 14:41 UTC, timuthy commented
@aaronfern can this be closed as cronjobs won't be used anymore?

2021-11-08 04:48 UTC, aaronfern commented
Yes, this isn't needed anymore. Closing 
/close

2021-11-08 04:48 UTC, closed without merging