Create member, delta/full-snapshot `Leases`
gardener/etcd-druid pull request #254
Opened 2021-11-04 16:46 UTC by timuthy

**How to categorize this PR?**

/area control-plane
/kind enhancement

**What this PR does / why we need it**:
This PR adds member, full snapshot and delta snapshot `Leases` which are maintained by `etcd-backup-restore`.

**Which issue(s) this PR fixes**:
Fixes part of #158

**Special notes for your reviewer**:
A "component" concept was introduced in this PR which in the long run can replace the chart that we use and instead build the K8s resources within the code to achieve a better test-ability. The same approach was taken in `gardener/gardener`.

**Release note**:

```feature operator
Etcd-Druid now creates member `Lease` objects which enables the heartbeat functionality for etcd members.
```
```feature operator
Etcd-Druid now creates delta-snapshot and full-snapshot `Lease` objects if backups are enabled. This is necessary in order to run compaction `Job`s.
```

2021-11-09 08:46 UTC, stoyanr requested changes
As a general comment, I am a bit intimidated by the `Etcd` component that is introduced in this PR. Yes, it's fairly small now, but it already makes a commitment to refactoring the `Etcd` controller in a similar fashion in the future, which is a rather huge refactoring. Until this done, the unfinished `Etcd` component will stick out badly and beg for attention. 

Also, the way components are used here is markedly different from the way they are used in g/g. Here, the `Etcd` component is basically taking over part of the `Reconcile`. In g/g, components are responsible for deploying / destroying / waiting upon specific objects such as extensions, dns resources, k8s resources such as deployments and services, etc. that have to be deployed / destroyed as part of the very complex shoot reconciliation.

I would propose a somewhat different approach that is equally good (or better) in terms of modularity / testability but avoids making such commitments, and is also much more similar to the way components are used in g/g. Instead of an `Etcd` component, we could introduce a `Lease` component to actually create / update / delete an individual lease, and perhaps a `MemberLease` to capture member lease specifics, as well as helper functions such as `DeployOrDestroyLease` and `DeployOrDestroyMemberLeases` with the logic currently in the respective `Etcd` methods. The controller will then call these functions (in the future, perhaps as part of a flow, as in the g/g shoot controller).

2021-11-09 08:46 UTC, stoyanr commented on pkg/component/etcd/etcd.go
> +	GetFullSnapshotLeaseName() string
I think these methods should be removed. Instead, `DeltaSnapshotLeaseName` and `FullSnapshotLeaseName` could be added to `Values`, set together with other `Values` fields and used wherever needed. This is also the approach used in most g/g components. `Get` methods should be used only when it's not possible to know a value in advance, e.g. you need to actually deploy an object in order to get a value from its status.

2021-11-09 08:46 UTC, stoyanr commented on pkg/component/etcd/leases.go
> +func (e *etcd) reconcileLease(ctx context.Context, lease *coordinationv1.Lease, enabled bool) error {
This method is not reconciling a Lease object, just creating, updating, or deleting it (as part of the reconcilation of an Etcd object). The actual reconciliation of a Lease will be performed by the respective controller. Let's use a name that matches more closely what this method is doing. I propose `deployOrDestroy` here though I guess `deploy`, `update` or `createOrUpdate` would also be ok - but not `reconcile` which has a very different meaning and is therefore confusing.

```suggestion
func (e *etcd) deployOrDestroyLease(ctx context.Context, lease *coordinationv1.Lease, enabled bool) error {
```

2021-11-09 08:46 UTC, stoyanr commented on pkg/component/etcd/leases.go
> +func (e *etcd) reconcileMemberLease(ctx context.Context) error {
This method is not reconciling a Lease object, it's creating, updating, or deleting multiple Lease objects (as part of the reconcilation of an Etcd object). The actual reconciliation of the Leases will be performed by the respective controller. Let's use a name that matches more closely what this method is doing. I propose `deployOrDestroy` here though I guess `deploy`, `update` or `createOrUpdate` would also be ok - but not `reconcile` which has a very different meaning and is therefore confusing.

```suggestion
func (e *etcd) deployOrDestroyMemberLeases(ctx context.Context) error {
```

2021-11-09 08:46 UTC, stoyanr commented on controllers/etcd_controller.go
> +		etcdValues["heartbeatDuration"] = etcd.Spec.Etcd.MemberHeartbeat
Nit: Could we have matching names here, e.g. either both "heartbeatDuration" or both "memberHeartbeat" (or "memberHeartbeatDuration")?

2021-11-09 08:46 UTC, stoyanr commented on pkg/component/etcd/etcd.go
> +func (e *etcd) Deploy(ctx context.Context) error {
Could you add doc comments on these exported methods? (`Deploy`, `Destroy`, etc.)

2021-11-09 08:46 UTC, stoyanr commented on pkg/component/etcd/etcd.go
> +}
Why is `Destroy` not implemented? Shouldn't it delete all the leases deployed by `Deploy`?

2021-11-12 12:45 UTC, timuthy commented
I will continue working on this PR after the `v0.7.0` release and further modularize as suggested by @stoyanr.

2021-11-25 07:24 UTC, timuthy commented
Let's continue with #262 which I filed because of the many changes in the code base that happened in the meantime. @stoyanr I addressed your comments there. Please let me know if it goes into the intended direction.
/close

2021-11-25 07:24 UTC, closed without merging