Fix accidental member lease deletion
gardener/etcd-druid pull request #353
Opened 2022-06-03 13:48 UTC by timuthy

**How to categorize this PR?**

/area control-plane
/kind bug

**What this PR does / why we need it**:
This PR fixes an issue with the member lease handling when leases are deleted by accident in unrelated namespaces. It also enables the member lease renewals again.

**Which issue(s) this PR fixes**:
Fixes #320
Fixes #332

**Special notes for your reviewer**:
/invite @ishan16696 

**Release note**:

```bugfix operator
An bug has been fixed that deleted member `lease` objects in all namespaces.
```

2022-06-03 14:23 UTC, ishan16696 requested changes

2022-06-03 14:23 UTC, ishan16696 commented on charts/etcd/templates/etcd-statefulset.yaml
> +        - --enable-member-lease-renewal=true
Please also make `--enable-member-lease-renewal=true` for unit tests

2022-06-03 14:25 UTC, ishan16696 commented on charts/etcd/templates/etcd-statefulset.yaml
> +        - --enable-member-lease-renewal=true
[here](https://github.com/gardener/etcd-druid/blob/master/controllers/etcd_controller_test.go#L1620) and [here](https://github.com/gardener/etcd-druid/blob/master/controllers/etcd_controller_test.go#L1205)

2022-06-05 04:48 UTC, ishan16696 requested changes

2022-06-05 04:48 UTC, ishan16696 commented on pkg/component/etcd/lease/lease_test.go
> +func memberLease(etcd *druidv1alpha1.Etcd, replica int, withOwnerRef bool) coordinationv1.Lease {
you didn’t use `withOwnerRef` bool anywhere. Am I missing something ?

2022-06-07 07:23 UTC, timuthy commented
Thanks a lot for the review @ishan16696 and the pointers. I addressed all comments, PTAL.

2022-06-07 08:02 UTC, merged