Add etcd network latency analysis
gardener/etcd-druid pull request #383
Opened 2022-07-26 08:45 UTC by seshachalam-yv

**How to categorize this PR?**

/area documentation

**What this PR does / why we need it**:
This PR captures the etcd network latency analysis for single node and mult-node.

**Release note**:

```other operator
NONE
```

2022-07-26 08:45 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/gardener/etcd-druid?pullRequest=383) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/gardener/etcd-druid?pullRequest=383) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/gardener/etcd-druid?pullRequest=383) it.</sub>

2022-08-01 06:28 UTC, aaronfern requested changes
Thanks for the PR @seshachalam-yv!
Just a few minor suggestions from me

2022-08-01 06:28 UTC, aaronfern commented on docs/etcd-network-latency.md
> +    * *Compare to `follower`, `leader` latency is less.*
```suggestion
    * *Compare to `follower`, `leader` has lower latency.*
```

2022-08-01 06:28 UTC, aaronfern commented on docs/etcd-network-latency.md
> +    * `mn-etcd-sz` latency(`~71.81ms`) is less than `mn-etcd-mz`(`~72.5ms`) but the difference is not much.
```suggestion
    * `mn-etcd-sz` latency(`~71.81ms`) is less than `mn-etcd-mz`(`~72.5ms`) but the difference is negligible.
```

2022-08-01 06:28 UTC, aaronfern commented on docs/etcd-network-latency.md
> +    * *Compare to `leader`, `follower` latency is less*.
```suggestion
    * *Compare to `leader`, `follower` has lower latency*. 
```

2022-08-01 06:28 UTC, aaronfern commented on docs/etcd-network-latency.md
> +    * `sn-etcd-sz` latency(`~16.35ms`) is **~20% less than** `mn-etcd-sz`(`~20.64ms`).
```suggestion
    * `sn-etcd-sz` latency(`~16.35ms`) is **~20% lesser than** `mn-etcd-sz`(`~20.64ms`).
```

2022-08-01 06:28 UTC, aaronfern commented on docs/etcd-network-latency.md
> +    * `mn-etcd-sz` latency(`~20.64ms`) is less than `mn-etcd-mz`(`~21.08ms`) but the difference is not much..
```suggestion
    * `mn-etcd-sz` latency(`~20.64ms`) is less than `mn-etcd-mz`(`~21.08ms`) but the difference is negligible..
```

2022-08-01 06:28 UTC, aaronfern commented on docs/etcd-network-latency.md
> +    * *Compare to `follower`, `leader` latency is less*.
```suggestion
    * *Compare to `follower`, `leader` has lower latency*.
```

2022-08-01 06:28 UTC, aaronfern commented on docs/etcd-network-latency.md
> +    * `mn-etcd-sz` latency(`~4.000secs`) is less than `mn-etcd-mz`(`~ 4.09secs`) but the difference is not much.
```suggestion
    * `mn-etcd-sz` latency(`~4.000secs`) is less than `mn-etcd-mz`(`~ 4.09secs`) but the difference is negligible.
```

2022-08-01 06:28 UTC, aaronfern commented on docs/etcd-network-latency.md
> +    * *Compare to `leader`, `follower` latency is less*.
```suggestion
    * *Compare to `leader`, `follower` has lower latency*. 
```

2022-08-01 06:28 UTC, aaronfern commented on docs/etcd-network-latency.md
> +    * `mn-etcd-sz` latency(`~0.67ms`) is  **~20% less than** `mn-etcd-mz`(`~0.85ms`).
```suggestion
    * `mn-etcd-sz` latency(`~0.67ms`) is  **~20% lesser than** `mn-etcd-mz`(`~0.85ms`).
```

2022-08-01 06:28 UTC, aaronfern commented on docs/etcd-network-latency.md
> +    * `mn-etcd-sz` latency(`~1.3ms`) is  **~20% less than** `mn-etcd-mz`(`~1.6ms`).
```suggestion
    * `mn-etcd-sz` latency(`~1.3ms`) is  **~20% lesser than** `mn-etcd-mz`(`~1.6ms`).
```

2022-08-01 06:28 UTC, aaronfern commented on docs/etcd-network-latency.md
> +    * `mn-etcd-sz` latency(`~73.95ms`) is  **more or less equal** `mn-etcd-mz`(`~ 73.8ms`).
```suggestion
    * `mn-etcd-sz` latency(`~73.95ms`) is  **more or less equal to** `mn-etcd-mz`(`~ 73.8ms`).
```

2022-08-01 06:28 UTC, aaronfern commented on docs/etcd-network-latency.md
> +    * Compare to consistency `Linearizable`, `Serializable` is **~20% less** for all cases
```suggestion
    * Compare to consistency `Linearizable`, `Serializable` is **~20% lesser** for all cases
```

2022-08-01 06:28 UTC, aaronfern commented on docs/etcd-network-latency.md
> +    * `sn-etcd-sz` latency(`~69.37ms`) is  **more or less equal** `mn-etcd-sz`(`~69.89ms`).
```suggestion
    * `sn-etcd-sz` latency(`~69.37ms`) is  **more or less equal to** `mn-etcd-sz`(`~69.89ms`).
```

2022-08-01 06:28 UTC, aaronfern commented on docs/etcd-network-latency.md
> +    * `mn-etcd-sz` latency(`~60.69ms`) is **~20% less than** `mn-etcd-mz`(`~70.76ms`).
```suggestion
    * `mn-etcd-sz` latency(`~60.69ms`) is **~20% lesser than** `mn-etcd-mz`(`~70.76ms`).
```

2022-08-01 06:28 UTC, aaronfern commented on docs/etcd-network-latency.md
> +    * Compare to  `leader`, `follower` read request latency is less.
```suggestion
    * Compare to  `leader`, `follower` has lower read request latency.    
```

2022-08-01 06:28 UTC, aaronfern commented on docs/etcd-network-latency.md
> +    * `sn-etcd-sz` latency(`~678.77ms`) is **~5% slightly less than** `mn-etcd-sz`(`~697.29ms`).
```suggestion
    * `sn-etcd-sz` latency(`~678.77ms`) is **~5% slightly lesser than** `mn-etcd-sz`(`~697.29ms`).
```

2022-08-01 06:28 UTC, aaronfern commented on docs/etcd-network-latency.md
> +    * `mn-etcd-sz` latency(`~697.29ms`) is less than `mn-etcd-mz`(`~701ms`) but the difference is not much.
```suggestion
    * `mn-etcd-sz` latency(`~697.29ms`) is less than `mn-etcd-mz`(`~701ms`) but the difference is negligible.
```

2022-08-01 06:28 UTC, aaronfern commented on docs/etcd-network-latency.md
> +    * `sn-etcd-sz` latency(`~687.36ms`) is less than `mn-etcd-sz`(`~692.68ms`) but the difference is not much.
```suggestion
    * `sn-etcd-sz` latency(`~687.36ms`) is less than `mn-etcd-sz`(`~692.68ms`) but the difference is negligible.
```

2022-08-01 06:28 UTC, aaronfern commented on docs/etcd-network-latency.md
> +    * `mn-etcd-sz` latency(`~692.68ms`) is **~5% slightly less than** `mn-etcd-mz`(`~735.7ms`).
```suggestion
    * `mn-etcd-sz` latency(`~692.68ms`) is **~5% slightly lesser than** `mn-etcd-mz`(`~735.7ms`).
```

2022-08-01 06:28 UTC, aaronfern commented on docs/etcd-network-latency.md
> +    * `sn-etcd-sz` latency(`~5.96ms`) is **~5% less than** `mn-etcd-sz`(`~6.28ms`).
```suggestion
    * `sn-etcd-sz` latency(`~5.96ms`) is **~5% lesser than** `mn-etcd-sz`(`~6.28ms`).
```

2022-08-01 06:28 UTC, aaronfern commented on docs/etcd-network-latency.md
> +    * `sn-etcd-sz` latency(`~1.593secs`) is **~20% less than** `mn-etcd-sz`(`~1.974secs`).
```suggestion
    * `sn-etcd-sz` latency(`~1.593secs`) is **~20% lesser than** `mn-etcd-sz`(`~1.974secs`).
```

2022-08-01 06:28 UTC, aaronfern commented on docs/etcd-network-latency.md
> +    * `sn-etcd-sz` latency(`~8.993secs`) is **~3% slightly less than** `mn-etcd-sz`(`~9.236secs`).
```suggestion
    * `sn-etcd-sz` latency(`~8.993secs`) is **~3% slightly lower than** `mn-etcd-sz`(`~9.236secs`).
```

2022-08-01 06:28 UTC, aaronfern commented on docs/etcd-network-latency.md
> +    * `mn-etcd-sz` latency(`~9.236secs`) is  **~2% slightly less than** `mn-etcd-mz`(`~9.100secs`).
```suggestion
    * `mn-etcd-sz` latency(`~9.236secs`) is  **~2% slightly lower than** `mn-etcd-mz`(`~9.100secs`).
```

2022-08-01 07:46 UTC, seshachalam-yv commented
Thanks for review @aaronfern

2022-08-01 08:16 UTC, aaronfern commented
/cla

2022-08-04 06:11 UTC, aaronfern approved these changes
/lgtm

2022-08-04 06:11 UTC, merged