Enabled e2e tests to read KUBECONFIG from environment variables and in-cluster variables
gardener/etcd-druid pull request #511
Opened 2023-01-16 07:06 UTC by abdasgupta

**How to categorize this PR?**

/area TODO
/kind TODO

**What this PR does / why we need it**:

**Which issue(s) this PR fixes**:
Fixes #

**Special notes for your reviewer**:

**Release note**:

```other operator

```

2023-01-16 07:48 UTC, abdasgupta commented
cc @seshachalam-yv

2023-01-16 08:09 UTC, ishan16696 commented
Ok, I will test this PR but how this PR is fixing #429 as mentioned in the PR description ?

2023-01-16 08:32 UTC, abdasgupta commented
> Ok, I will test this PR but how this PR is fixing #429 as mentioned in the PR description ?

Sorry! My bad. I updated with the correct issue

2023-01-16 08:43 UTC, ishan16696 commented
> I updated with the correct issue

 it is part of #465 but won't fixes the #465 right ?

2023-01-16 09:08 UTC, shreyas-s-rao requested changes
@abdasgupta thanks for your PR. Please add the `area` and `kind` labels to this PR, in line with best practices for this repo. Please also update the PR note to `Fixes partially #465`, because this PR does not fully fix issue #465. Let's close that issue only after the story is complete.

Now coming to the PR itself, you mention that `this is PR is raised which enables to run e2e tests with kubeconfigs provided by either environment variables or through in-cluster variables`, but this PR completely removes support for specifying KUBECONFIG env var for running tests locally against any arbitrary k8s cluster, which is still necessary for local testing. Please enhance the PR to allow both methods of getting restConfig for the k8s cluster. Hint: if KUBECONFIG env var is not present or is empty, then default to trying using in-cluster kubeconfig.

2023-01-16 09:08 UTC, shreyas-s-rao commented on test/e2e/utils.go
> +	return cl, nil
I don't see any need for making changes to this code. The previous implementation of `return client.New(config, client.Options{})` was absolutely fine and neat to read as well. The new code introduced here simply does the exact same thing that the previous code did, but with more lines of unnecessary code. Please revert this change.

2023-01-17 08:31 UTC, abdasgupta commented
This PR does not fully resolve #465. Though it enabled reading KUBECONFIG from in-cluster as well as environment variables but it is not a must have requirement for now. I am closing this PR in favour of https://github.com/gardener/etcd-druid/pull/513 .. Will reopen the issue if reading kubeconfig from in-cluster variables are necessary in future
/close

2023-01-17 08:31 UTC, closed without merging