Fix setting `ownerReference` on copy backups `Job`
gardener/etcd-druid pull request #533
Opened 2023-02-20 09:42 UTC by timebertt

**How to categorize this PR?**

/area quality
/kind bug

**What this PR does / why we need it**:

Fix setting `ownerReference` on copy backups `Job`:
Instead of using helm for setting the `ownerReference`, use proper go code that won't mess up the leading `0` 😄 

**Which issue(s) this PR fixes**:
Fixes https://github.com/gardener/etcd-druid/issues/532

**Special notes for your reviewer**:

**Release note**:

```bugfix user
A bug that caused control plane migrations to fail for shoots with numeric names and a leading `0` has been fixed.
```

2023-02-22 08:38 UTC, unmarshall approved these changes

2023-02-27 11:23 UTC, shreyas-s-rao requested changes
@timebertt thanks for fixing this bug! Can you maybe add a test to ensure that we don't run into a possible regression in the future? Thanks! Other than that, LGTM

2023-03-09 07:49 UTC, timebertt commented
@shreyas-s-rao sure thing!
I added a test case and verified that it fails on master:

```
• [FAILED] [60.019 seconds]
EtcdCopyBackupsTask Controller
/Users/ebertti/go/src/github.com/gardener/etcd-druid/controllers/etcdcopybackupstask_controller_test.go:41
  when creating and deleting etcdcopybackupstask
  /Users/ebertti/go/src/github.com/gardener/etcd-druid/controllers/etcdcopybackupstask_controller_test.go:52
    [It] should correctly handle ownerReferences for numeric names with leading 0
    /Users/ebertti/go/src/github.com/gardener/etcd-druid/controllers/etcdcopybackupstask_controller_test.go:129

  Begin Captured GinkgoWriter Output >>
    [BeforeEach] EtcdCopyBackupsTask Controller
      /Users/ebertti/go/src/github.com/gardener/etcd-druid/controllers/etcdcopybackupstask_controller_test.go:47
    [It] should correctly handle ownerReferences for numeric names with leading 0
      /Users/ebertti/go/src/github.com/gardener/etcd-druid/controllers/etcdcopybackupstask_controller_test.go:129
    1.678347944842623e+09	DEBUG	etcd-copy-backups-task-controller	Adding finalizer	{"task": "default/01234", "operation": "reconcile"}
    1.678347944844933e+09	DEBUG	etcd-copy-backups-task-controller	Reconciling creation or update	{"task": "default/01234", "operation": "reconcile"}
    1.678347944847269e+09	INFO	etcd-copy-backups-task-controller	Creating job	{"task": "default/01234", "operation": "reconcile", "job": "default/01234-worker"}
    1.6783479448492959e+09	DEBUG	etcd-copy-backups-task-controller	Creation or update reconciled	{"task": "default/01234", "operation": "reconcile"}
  << End Captured GinkgoWriter Output

  Timed out after 60.000s.
  Expected
      <string>: Job
  to match fields: {
  [.ObjectMeta.OwnerReferences:
  	unexpected element 668, .ObjectMeta.OwnerReferences:
  	missing expected element 01234]
  }

  In [It] at: /Users/ebertti/go/src/github.com/gardener/etcd-druid/controllers/etcdcopybackupstask_controller_test.go:77
```

2023-03-09 10:55 UTC, shreyas-s-rao commented
Thanks a lot @timebertt !
/ok-to-test
/lgtm

2023-03-09 11:06 UTC, shreyas-s-rao commented
I see the following error for the tests:
```
> Check
Executing golangci-lint
/tmp/build/a94a8fe5/pull-request-gardener.etcd-druid-master-pr/vendor/github.com/gardener/gardener/hack/check.sh: line 33:  7020 Killed                  golangci-lint run $GOLANGCI_LINT_CONFIG_FILE --timeout 10m $@
make: *** [Makefile:84: check] Error 137
```

@unmarshall is this related to the recent upgrade to golang 1.20 on master?

2023-03-13 08:29 UTC, shreyas-s-rao commented
/reviewed ok-to-test

2023-03-13 12:55 UTC, seshachalam-yv commented
@timebertt
This will be fixed as part of issue https://github.com/gardener/etcd-druid/issues/552, as we are eliminating the Helm chart.
/hold

2023-03-13 13:25 UTC, timebertt commented
@seshachalam-yv 
I assume it will take some time to perform the refactoring. Would you mind merging my fix for a real world problem now already?

2023-03-13 14:49 UTC, shreyas-s-rao commented
@timebertt if this is urgent, then we can go ahead with the fix. Can you please rebase on latest master? You might have to see #506 which refactors/restructures the druid code base considerably. For instance, `controllers/etcdcopybackupstask_controller.go` and `controllers/etcdcopybackupstask_controller_test.go` have moved to `controllers/etcdcopybackupstask/*`. I think the rebase will fix the failing tests too. FYI, #542 moves druid to go 1.20, so you might have to keep that in mind for your local dev environment.

/unhold

2023-03-16 10:43 UTC, timebertt commented
Done, PTAL :)

2023-03-16 14:35 UTC, shreyas-s-rao commented
Hi @timebertt . As @seshachalam-yv mentioned, he has already raised #553 a couple of days ago to fix issue #552 , which now creates the job using go code and eliminates the helm charts entirely. As part of this change, the controller sets owner reference on the job using `controllerutil.SetControllerReference()` the same way your PR does, and also adds the test case to test numeric task names with leading zero. I would vote for closing this PR in favour of that one, since it now also fixes #532.

WDYT? If you can review PR #553 and confirm that it fixes your issue, we can merge it and include it in the upcoming release of etcd-druid.

2023-03-17 07:22 UTC, timebertt commented
This is disappointing. Especially because it took some time to rebase this PR. This was some "unfortunate" communication, but whatever.
#553 will fix the issue. As this is my goal:
/close

2023-03-17 07:23 UTC, closed without merging

2023-04-06 05:58 UTC, shreyas-s-rao commented
@timebertt your fix is included in druid v0.17 as part of https://github.com/gardener/etcd-druid/pull/553. Again, apologies for the miscommunication from our side. Our intent was to avoid making your changes redundant with our new PR which anyway changes the way the job resource is deployed. But it ended up adding more work on your side. 😞