Simplify `Localstack` setup by utilizing S3 endpoint support
gardener/etcd-druid pull request #713
Opened 2023-10-17 09:55 UTC by seshachalam-yv

**How to categorize this PR?**

/area dev-productivity
/area documentation
/kind enhancement

**What this PR does / why we need it**:
This PR simplifies the setup of LocalStack by leveraging the [recent support for passing the endpoint to S3](https://github.com/aws/aws-cli/issues/4012#issuecomment-1626114865). The changes include modifications to the configuration files and scripts to accommodate this latest support, making it easier to set up and use Localstack.

Previously, the AWS CLI didn't provide support to pass an endpoint for the S3 service, requiring a workaround of rewriting the DNS from CoreDNS. With the [recent support for passing the endpoint to S3](https://github.com/aws/aws-cli/issues/4012#issuecomment-1626114865), we were able to simplify the setup steps and remove the old workarounds.

- Added documentation on setting up `etcd-druid` with Localstack locally on a Kind cluster.
- Introduced new sample `druid_v1alpha1_etcd_localstack.yaml` for `etcd` CR with a Localstack store.
- Added new sample AWS secret `etcd-secret-localstack.yaml` for Localstack.

**Which issue(s) this PR fixes**:
Fixes #

**Special notes for your reviewer**:

**Release note**:

```feature developer
feature operator
Added documentation and sample configurations for simplifying Localstack setup, making it easier for developers to create a local testing environment using a Kind cluster.
```

2023-11-03 06:43 UTC, anveshreddy18 requested changes

2023-11-03 06:43 UTC, anveshreddy18 commented on docs/development/getting-started-locally-localstack.md
> +
Please  unset the `AWS_ENDPOINT_URL_S3` while cleaning up the setup

2023-11-06 16:46 UTC, abdasgupta approved these changes
Thanks for such a nice PR. I did not run the e2e tests with the changes. I think e2e tests should run fine with the changes in this PR. Still, before merging, run the e2e test once with this changes.

2023-11-07 13:17 UTC, abdasgupta commented
/lgtm

2023-11-09 11:11 UTC, anveshreddy18 approved these changes

2023-11-09 13:48 UTC, merged