Move feature:etcd-wrapper from alpha to beta feature.
gardener/etcd-druid pull request #744
Opened 2024-01-03 09:32 UTC by ishan16696

/kind enhancement

**What this PR does / why we need it**:
This PR moves `UseEtcdWrapper` alpha feature to beta feature by setting it as the default option in etcd-druid.

**Which issue(s) this PR fixes**:
Fixes Part1:  https://github.com/gardener/etcd-druid/issues/743

**Special notes for your reviewer**:

**Release note**:

```breaking operator
`EtcdWrapper` has progressed from the alpha stage to the beta stage, which now allows for its default usage in etcd-druid. If you prefer to continue using the etcd-custom-image, you can disable the EtcdWrapper by adjusting the feature flag
```

2024-01-03 10:20 UTC, ishan16696 commented
/test pull-etcd-druid-e2e-kind-alpha-features

2024-01-04 04:56 UTC, shreyas-s-rao requested changes
@ishan16696 thanks for the PR. Just one comment regarding the doc. PTAL

2024-01-04 04:56 UTC, shreyas-s-rao commented on docs/deployment/feature-gates.md
> +| `UseEtcdWrapper` | `true`  | `Beta`  | `0.22` |       |
```suggestion
| `UseEtcdWrapper` | `false` | `Alpha` | `0.19` | `0.21` |
| `UseEtcdWrapper` | `true`  | `Beta`  | `0.22` |        |
```

All stages of a feature gate need to be captured in this doc, similar to https://github.com/gardener/gardener/blob/master/docs/deployment/feature_gates.md

2024-01-04 09:47 UTC, shreyas-s-rao commented
@ishan16696 thanks for addressing my comment. Can you also take a look at https://github.com/gardener/ci-infra/pull/1080#discussion_r1441378749 and address that as well in this PR?

2024-01-04 11:39 UTC, ishan16696 commented
> @ishan16696 thanks for addressing my comment. Can you also take a look at https://github.com/gardener/ci-infra/pull/1080#discussion_r1441378749 and address that as well in this PR?

done, PTAL

2024-01-06 07:53 UTC, shreyas-s-rao approved these changes
@ishan16696 thanks for making the changes. 
/lgtm

In the future, we need a better way to activate specific feature gates and deactivate others. Ideally, we need to have different combinations of profiles like `alpha-on`, `alpha-on-beta-off`, `beta-off`, etc, so that when we have multiple feature-gates available in druid, we can test these quite well.

2024-01-06 08:00 UTC, merged