Make max-backups configurable in LimitBased GC from etcd yaml with a new field `maxBackupsLimitBased ` in Etcd CR
gardener/etcd-druid pull request #755
Opened 2024-01-11 07:01 UTC by anveshreddy18

**How to categorize this PR?**

/area usability
/kind enhancement

**What this PR does / why we need it**:

This PR adds a new field `maxBackupsLimitBased` in the `spec.backup` section of Etcd yaml and makes necessary changes, which allows to configure `max-backups` parameter used for LimitBased GC. 

- At present, there is no way to configure the number of full snapshots to retain in a limitBased GC policy as a default value of `7` is set in the code.
- This change will allow the user to configure the `--max-backups` flag of the etcd-statefulset thus allowing them to control the behaviour of Limit Based GC. 

**Note:** It will be an optional field, when not set, `max-backups` will defaul to `7`

**Which issue(s) this PR fixes**:
Fixes #754

**Special notes for your reviewer**:

**Release note**:

```other operator
Add a new "maxBackupsLimitBased" field to the "spec.backup" section of Etcd yaml
```

2024-01-19 03:37 UTC, ishan16696 commented
/test pull-etcd-druid-e2e-kind

2024-01-19 04:29 UTC, ishan16696 commented
/test pull-etcd-druid-e2e-kind

2024-01-22 12:06 UTC, ishan16696 requested changes
Thanks @anveshreddy18 for PR, overall PR looks good.
just few nits

2024-01-22 12:06 UTC, ishan16696 commented on api/v1alpha1/types_etcd.go
> +	// MaxBackupsLimitBasedGC defines the maximum number of Full snapshots to retain in Limit Based GC.
```suggestion
	// MaxBackupsLimitBasedGC defines the maximum number of Full snapshots to retain in Limit Based GarbageCollectionPolicy.
```

2024-01-22 12:24 UTC, ishan16696 commented
@anveshreddy18 I have also updated the release note. Please take a look. Hope that's fine.

2024-01-22 13:35 UTC, anveshreddy18 commented on pkg/component/etcd/statefulset/values_helper.go
> +		command = append(command, "--max-backups="+strconv.Itoa(int(pointer.Int32Deref(val.MaxBackupsLimitBasedGC, defaultMaxBackupsLimitBasedGC))))
Updated in the latest commit

2024-01-22 13:44 UTC, ishan16696 approved these changes
LGTM!!

2024-01-22 14:11 UTC, anveshreddy18 commented
/test pull-etcd-druid-e2e-kind

2024-01-22 14:36 UTC, anveshreddy18 commented
/test pull-etcd-druid-e2e-kind

2024-01-22 15:44 UTC, ishan16696 commented
/test pull-etcd-druid-e2e-kind

2024-01-22 16:26 UTC, anveshreddy18 commented
/test pull-etcd-druid-e2e-kind

2024-01-22 18:04 UTC, ishan16696 commented
/test pull-etcd-druid-e2e-kind

2024-01-23 03:53 UTC, merged