Remove usage of *_STORAGE_API_ENDPOINT` environment variables for providers
gardener/etcd-druid pull request #856
Opened 2024-08-12 08:27 UTC by shreyas-s-rao

**How to categorize this PR?**

/area security
/kind task

**What this PR does / why we need it**:
Remove usage of *_STORAGE_API_ENDPOINT` environment variables for providers, since credentials from secrets (including API endpoints) should not be passed as environment variables to the backup-restore container.

**Which issue(s) this PR fixes**:
Fixes https://github.com/gardener/etcd-backup-restore/issues/727

**Special notes for your reviewer**:
/block
To be merged only after https://github.com/gardener/etcd-backup-restore/pull/759 is merged, released and etcdbr version v0.30.0 is updated in druid.
For local testing purpose, I have included the PR build image from https://concourse.ci.gardener.cloud/teams/gardener/pipelines/etcd-backup-restore-master/jobs/master-pull-request-job/builds/37. This commit will be removed before merging. 

@renormalize please let me know if we can pass `domain` to Azurite (with format `http(s)://<storageAccount>.<domain>`) instead of the entire URL.

**Release note**:

```noteworthy user
Remove usage of *_STORAGE_API_ENDPOINT` environment variables for Google and Azure providers. Storage API endpoint / domain will instead be directly consumed by etcd-backup-restore from the mounted backup secret.
```

2024-08-12 08:27 UTC, shreyas-s-rao commented
/assign @renormalize @unmarshall

2024-08-12 09:52 UTC, renormalize requested changes
Thanks for the PR @shreyas-s-rao!
Could you address the few TODOs that are remaining?

2024-08-12 09:52 UTC, renormalize commented on internal/images/images.yaml
> +  tag: "v0.30.0-dev-00e7d52969652e0390590750da06582ce6c336f5"
Could you revert this? Thanks.

2024-08-12 09:52 UTC, renormalize commented on test/e2e/utils.go
> +					// TODO: replace with `domain`
Can you address this TODO? Thanks.

2024-08-12 09:52 UTC, renormalize commented on config/samples/etcd-secret-azurite.yaml
> +  # TODO: replace with `domain`
Can you address this TODO? Thanks.

2024-08-14 05:38 UTC, renormalize commented
As discussed off GitHub with @shreyas-s-rao, passing domain in the `http(s)://<storageAccount>.<domain>` format is supported by Azurite.

The way to perform this is to add:

```
127.0.0.1 account1.blob.localhost
```

to the hosts file of the host machine where etcd-backup-restore tests are running so that `https://<storage-account>.blob.localhost` resolves to the Azurite process. One simply needs to pass the storage account name that is configured to be used for Azurite, and the `domain` as `blob.localhost`.

However, it has to be kept in mind to *not* pass the `disableProductStyleUrl` flag to Azurite at startup. More can be found [here](https://github.com/Azure/Azurite?tab=readme-ov-file#production-style-url).

Doing this will break the current way the Azurite make targets work in etcd-druid, so for a few commits Azurite will not be functional with etcd-druid for local development and testing.

2024-08-14 05:41 UTC, shreyas-s-rao commented
Added this as a point in #782

2024-08-14 05:41 UTC, shreyas-s-rao commented
/hold until https://github.com/gardener/etcd-backup-restore/pull/759 is merged, released and etcdbr version v0.30.0 is updated in druid.

2024-08-23 03:26 UTC, ashwani2k commented
/unhold as https://github.com/gardener/etcd-backup-restore/pull/759 is merged. 
@shreyas-s-rao  Shall we merge it?

2024-08-23 08:36 UTC, shreyas-s-rao commented
@ashwani2k I've removed the temp commit now, so the PR can be merged once the tests pass.

2024-08-23 09:04 UTC, shreyas-s-rao commented
/test pull-etcd-druid-e2e-kind

2024-08-23 09:06 UTC, shreyas-s-rao commented
@ashwani2k can you please raise a PR to update etcdbr image to v0.30.0 in images.yaml, along with the relevant release notes? I'm surprised that the PR was not raised automatically.

2024-08-23 09:34 UTC, shreyas-s-rao commented
/test pull-etcd-druid-e2e-kind-nondistroless-etcd

2024-09-09 04:37 UTC, shreyas-s-rao commented
@ashwani2k I have rebased the PR, so it can now be merged, after the tests pass of course.

2024-09-09 04:49 UTC, ashwani2k approved these changes

2024-09-09 06:36 UTC, renormalize approved these changes
Tested with the `v0.30.1` of etcd-backup-restore, and all behavior is as expected. Thanks.

2024-09-09 07:09 UTC, merged