DEP: Design proposal for OnDelete Strategy
gardener/etcd-druid pull request #879
Opened 2024-09-23 08:52 UTC by anveshreddy18

**How to categorize this PR?**

/area documentation
/kind enhancement

**What this PR does / why we need it**:
This PR adds the enhancement proposal for `OnDelete` update strategy  undertaken by `etcd-druid`. 

**Which issue(s) this PR fixes**:
Writes proposal for #588 

**Special notes for your reviewer**:

**Release note**:

```doc operator
Introduce DEP-06: Druid controlled pod updates with the help of StatefulSet OnDelete Strategy
```

2025-03-10 10:34 UTC, shreyas-s-rao commented
/assign @shreyas-s-rao @unmarshall

2026-04-14 10:59 UTC, ishan16696 requested changes
Thanks @anveshreddy18 , few comments from my initial look.

2026-04-14 10:59 UTC, ishan16696 commented on docs/proposals/06-sts-ondelete-strategy.md
> +- **[RollingUpdate](https://kubernetes.io/docs/concepts/workloads/controllers/statefulset/#rolling-updates)**: A statefulset update strategy that updates the pods one by one in a rolling fashion.
```suggestion
- **[RollingUpdate](https://kubernetes.io/docs/concepts/workloads/controllers/statefulset/#rolling-updates)**: A statefulset update strategy that updates the pods from the largest ordinal to the smallest in a rolling fashion.
```

2026-04-14 10:59 UTC, ishan16696 commented on docs/proposals/06-sts-ondelete-strategy.md
> +- **Leader**: The member of the etcd cluster that is responsible for handling all the client requests and replicating the data to the followers.
Leader doesn't handle all the client request, technically it only handles all write req and read req can be served by any voting member.
```suggestion
- **Leader**: The member of the etcd cluster that is responsible for handling all the write requests and replicating the data to its followers.
```

2026-04-14 10:59 UTC, ishan16696 commented on docs/proposals/06-sts-ondelete-strategy.md
> +- **Learner**: The member of the etcd cluster that does not participate in the quorum and is used for learning the data from the leader.
```suggestion
- **Learner**: The non-voting member of the etcd cluster that does not participate in the leader-election and is used for learning the data from the leader.
```

2026-04-14 10:59 UTC, ishan16696 commented on docs/proposals/06-sts-ondelete-strategy.md
> +- This design document proposes the introduction of a feature gate in the `etcd-druid` operator. The feature gate is intended to provide users with the ability to select the `OnDelete` update strateg
why a feature-gate ? why not configure it via Etcd api 🤔 by which operator can choose which update strategy they want to use, we can set and change the default strategy.

2026-04-14 10:59 UTC, ishan16696 commented on docs/proposals/06-sts-ondelete-strategy.md
> +1. **etcd container**: Runs the etcd process. The health of the etcd container is evaluated using a [readiness probe](https://kubernetes.io/docs/concepts/configuration/liveness-readiness-startup-prob
```suggestion
1. **etcd container**: Runs the etcd process. The health of the etcd container is evaluated using a [readiness probe](https://kubernetes.io/docs/concepts/configuration/liveness-readiness-startup-probes/#readiness-probe). This probe checks if the etcd container is ready to serve incoming traffic.
```

2026-04-14 10:59 UTC, ishan16696 commented on docs/proposals/06-sts-ondelete-strategy.md
> +2. **backup-restore container**: Operates as a sidecar to the etcd container. No readiness probe is defined for the backup-restore container. Its health is not a primary concern post-initialization s
```suggestion
2. **backup-restore container**: Operates as a sidecar to the etcd container. No readiness probe is defined for the backup-restore container. Its health is not a primary concern post-initialization of etcd member since it does not impact the etcd cluster.
```

2026-04-14 10:59 UTC, ishan16696 commented on docs/proposals/06-sts-ondelete-strategy.md
> +In the context of the `OnDelete` update strategy, the health assessment is focused solely on the etcd container. This is because, post-initialization, the backup sidecar's health does not impact the
```suggestion
In the context of the `OnDelete` update strategy, the health assessment is focused solely on the etcd container. This is because, post-initialization, the backup sidecar's health does not impact the etcd's quorum. There is a possibility of the sidecar container becoming unhealthy which may falsely indicate that the pod can be deleted to update it, but has the risk of losing quorum. `backup-restore` container's health is not a significant concern as the etcd container is the primary entity responsible for handling traffic and maintaining the quorum. The primary objective of the `OnDelete` strategy is to prevent potential permanent or transient quorum loss, not to ensure the `backup-restore` sidecar container's health.
```

2026-04-14 10:59 UTC, ishan16696 commented on docs/proposals/06-sts-ondelete-strategy.md
> +For a three-member etcd cluster, the PDB `minAvailable` is set to `2` to ensure the availability of at least two pods at any given time to maintain quorum. This configuration permits the `OnDelete` p
> This configuration permits the `OnDelete` process to evict only a single pod at any time from a three-member etcd cluster

unlike PDB "OnDelete" doesn't uses eviction API ... then why you have mentioned this ....I didn't get this part.

2026-04-14 10:59 UTC, ishan16696 commented on docs/proposals/06-sts-ondelete-strategy.md
> +In a single-node etcd scenario, the PDB `.spec.minAvailable` is set to `0`, but the pod carries a CA annotation `cluster-autoscaler.kubernetes.io/safe-to-evict` set to `false`. This configuration pre
```suggestion
In a single-node etcd scenario, the PDB `.spec.minAvailable` is set to `0`, but the pod carries a CA annotation `cluster-autoscaler.kubernetes.io/safe-to-evict` set to `false`. This configuration prevents the pod from being evicted by the cluster autoscaler during voluntary disruptions. However, the pod remains susceptible to eviction by the Vertical Pod Autoscaler (VPA) as it uses eviction API call, thus allowing the `OnDelete` process to evict the pod if necessary.
```

2026-04-23 15:13 UTC, shreyas-s-rao requested changes
@anveshreddy18 thanks a lot for the well-written PR. Some comments from me:

2026-04-23 15:13 UTC, shreyas-s-rao commented on docs/proposals/06-sts-ondelete-strategy.md
> +This proposal recommends changing the StatefulSet update strategy used by etcd-druid from `RollingUpdate` to `OnDelete`. With `OnDelete`, the Kubernetes StatefulSet controller no longer automatically
```suggestion
This proposal recommends supporting the `OnDelete` update strategy to be used by etcd-druid to update the StatefulSet pods backing the Etcd cluster members. With `OnDelete`, the Kubernetes StatefulSet controller no longer automatically restarts pods when the pod template changes. Instead, a new dedicated controller in etcd-druid takes responsibility for deleting and recreating pods in a carefully chosen order that accounts for etcd member health and cluster role. The goal is to prevent unintended quorum loss during spec updates to the Etcd cluster.
```

2026-04-23 15:13 UTC, shreyas-s-rao commented on docs/proposals/07-sts-ondelete-strategy.md
> +- **Non-participating pod**: A pod whose etcd container is not part of the quorum (the member may be down, restarting, or not yet joined).
Still a bit unclear about this. A member may be restarting, but would still be part of the quorum right? Wouldn't that make it a participating pod? A member that's not yet joined (or is a learner) is clearly a non-participating pod, but it seems like a member that's down (unhealthy) would also still be part of the quorum - just that if one member is down in a 3-member cluster, then only 2 members are healthy, and if 2 are down, then the cluster has lost quorum.

Please clarify this.

2026-04-23 15:13 UTC, shreyas-s-rao commented on docs/proposals/assets/07-rolling-update-state-diagram.png
Nit: there's a "YES" missing on the arrow from `Is this the original unhealthy pod` and `Wait for pod to be ready`

2026-04-23 15:13 UTC, shreyas-s-rao commented on docs/proposals/06-sts-ondelete-strategy.md
> +- **Default value**: `OnDelete`
Shouldn't the default be `RollingUpdate`, to not break the current behaviour? Eventually it can be defaulted to `OnDelete`, maybe a few releases later, but not from the very beginning. Can you please mention this as a note maybe?

2026-04-23 15:13 UTC, shreyas-s-rao commented on docs/proposals/06-sts-ondelete-strategy.md
> +The decision to use a spec field instead of a feature gate is documented in [Decision Record 003](../decisions/003-ondelete-as-spec-field-not-feature-gate.md). The key reasons are: per-cluster contro
I don't see this decision record file in the PR or in your fork. Please add it.

2026-04-23 15:13 UTC, shreyas-s-rao commented on docs/proposals/06-sts-ondelete-strategy.md
> +- The update process may span multiple reconciliation cycles (waiting for pods to come back, checking health, proceeding to the next pod). Embedding this in the StatefulSet component would make it a
One could also argue that there are many long-running operations in the Etcd reconciliation loop today, but the pattern we've adopted is to actuate a change, requeue after some time, check whether that change has taken effect, [requeue again if not done yet], then proceed with the next step. Same logic would be applicable for the OnDelete logic too, so technically this could have been part of the statefulset component.

Does having two controllers lead to any possible race conditions? I just want to rule out such a possibility before we go ahead.

2026-04-23 15:13 UTC, shreyas-s-rao commented on docs/proposals/07-sts-ondelete-strategy.md
> +The controller processes one pod per reconciliation cycle. After updating a pod, it requeues and waits for the pod to come back before proceeding to the next one. This ensures that the cluster is nev
This also ensures that the reconciler is not waiting on a pod to get recreated, so we don't block a reconciler thread for each cluster update. Can you add this as a benefit too?

2026-04-23 15:13 UTC, shreyas-s-rao commented on docs/proposals/06-sts-ondelete-strategy.md
> +| Second | Leader | Deleting the leader triggers an election, so it is done last. |
I remember we had discussed long ago about manually moving the leader before updating the leader pod, so that we don't trigger a leader election at all, but gracefully move leadership and avoid even that intermittent leader election downtime. Can that be added here?

How do we move the leader? A very simple move-leader call to the leader etcd endpoint, possibly via an `EtcdOpsTask`. If you don't want scope creep, can you please add this as a future enhancement? Or if this is not much effort to implement, it could be included in this DEP and implementation or feature completeness.

2026-04-23 15:13 UTC, shreyas-s-rao commented on docs/proposals/assets/07-OnDelete-StateDiagram.png
Nice visualisation.

2026-04-23 15:13 UTC, shreyas-s-rao commented on docs/proposals/07-sts-ondelete-strategy.md
> +**Switching from OnDelete to RollingUpdate:**
I wonder what would happen if there's an update currently in progress when this change is made. So OnDelete controller has just updated pod-1, when the `updateStrategy` is changed to `RollingUpdate`. Would sts controller now correctly update the remaining two pods (or maybe all the 3 pods)? Has this behaviour been tested?

2026-04-23 15:13 UTC, shreyas-s-rao commented on docs/proposals/07-sts-ondelete-strategy.md
> +**Switching from RollingUpdate to OnDelete:**
Same question as above. If there's an ongoing rolling update (that's stuck for some reason) and the strategy is changed to OnDelete, how would OnDelete controller handle it? I would assume this should work fine since it checks the pod controller-revision-hash to know which ones were already updated, and only considers the remaining un-updated ones for ondelete-style update, correct?

2026-04-23 15:13 UTC, shreyas-s-rao commented on docs/proposals/06-sts-ondelete-strategy.md
> +- `etcd_druid_ondelete_update_duration_seconds`: Time from the first detection of an `updateRevision` change to the completion of all pod updates. Labeled by etcd cluster name.
```suggestion
- `etcddruid_ondelete_update_duration_seconds`: Time from the first detection of an `updateRevision` change to the completion of all pod updates. Labeled by etcd cluster name.
```

This is the current convention, but if it seems wrong, we can discuss changing it in the current code too, during implementation.

2026-04-23 15:13 UTC, shreyas-s-rao commented on docs/proposals/06-sts-ondelete-strategy.md
> +- `etcd_druid_ondelete_reconcile_cycles_total`: Number of reconciliation cycles required to complete a full pod update. Labeled by etcd cluster name.
Same as above

2026-04-23 15:13 UTC, shreyas-s-rao commented on docs/proposals/06-sts-ondelete-strategy.md
> +### VPA and HVPA Interaction
Thanks for adding the section. There's no ned to mention HVPA, since it's no longer used.

2026-04-23 15:13 UTC, shreyas-s-rao commented on docs/proposals/06-sts-ondelete-strategy.md
> +  <img src="assets/06-OnDelete-StateDiagram-With-Etcdbr-Health.png" alt="OnDelete state diagram with backup-restore health awareness (future scope)" width="700">
I feel we don't need this diagram, it would just confuse readers of this DEP, since you state we don't worry about etcdbr health in this DEP.

2026-04-23 15:14 UTC, shreyas-s-rao commented
@anveshreddy18 please rebase the PR as well, to fix failing tests.

2026-04-23 16:53 UTC, ishan16696 requested changes

2026-04-23 16:53 UTC, ishan16696 commented on docs/proposals/06-sts-ondelete-strategy.md
> +This proposal recommends changing the StatefulSet update strategy used by etcd-druid from `RollingUpdate` to `OnDelete`. With `OnDelete`, the Kubernetes StatefulSet controller no longer automatically
```suggestion
This proposal recommends changing the StatefulSet update strategy used by etcd-druid from `RollingUpdate` to `OnDelete`. With `OnDelete`, the Kubernetes StatefulSet controller no longer automatically rollout the pods when the pod template changes. Instead, a new dedicated controller in etcd-druid takes responsibility for deleting and recreating pods in a carefully chosen order that accounts for etcd member health and cluster role. The goal is to prevent unintended quorum loss during pod updates.
```

2026-04-23 16:53 UTC, ishan16696 commented on docs/proposals/06-sts-ondelete-strategy.md
> +- **OnDelete**: A StatefulSet update strategy where pods are only updated when they are explicitly deleted. The StatefulSet controller does not automatically roll pods on template changes.
```suggestion
- **OnDelete**: A StatefulSet update strategy where pods are only updated when they are explicitly deleted. The StatefulSet controller does not automatically rollout the pods on template changes.
```

2026-04-23 16:53 UTC, ishan16696 commented on docs/proposals/07-sts-ondelete-strategy.md
> +- **Non-participating pod**: A pod whose etcd container is not part of the quorum (the member may be down, restarting, or not yet joined).
I'm not very much convinced with these 2 terminologies and their definitions. I understand what you're trying to say by defining "Participating and non-Participating pods" but IMO it's hard to define such state and to take decision on that basis as member pods can be temporary down as well as permanently down.
Now, Let's take case by case:
1. If member is temporary down (pod restart) then it will come up ... nothing to done from our side 🤷‍♂️ .
2. If member is permanently down then there will be 2 cases again:
    - If there is only 1 member down then single restoration will/should trigger, and it should come up as healthy.
    - If there is 1+ member are unhealthy then it's permanent quorum loss there nobody can't do anything, it require manual intervention.

2026-04-23 16:53 UTC, ishan16696 commented on docs/proposals/06-sts-ondelete-strategy.md
> +The StatefulSet controller starts from Pod N (the highest ordinal), terminates it, and waits for the new pod to become ready. If the terminated pod is not the originally unhealthy one, quorum is lost
Most likely it will be a transient quorum loss .. right as nth pod (highest ordinal) will eventually come-up  ?

2026-04-23 16:53 UTC, ishan16696 commented on docs/proposals/07-sts-ondelete-strategy.md
> +For a single-node etcd cluster, both `RollingUpdate` and `OnDelete` produce the same outcome since there is only one pod to update. The benefit of `OnDelete` is specific to multi-node clusters where
should we keep using `RollingUpdate` for singleton cluster as there is no effect of moving to `OnDelete` then why to make it complicated ?
On scale-up just the update the updateStrategy to `OnDelete`, wdyt ?
/cc @shreyas-s-rao

2026-04-23 16:53 UTC, ishan16696 commented on docs/proposals/06-sts-ondelete-strategy.md
> +The details of the PVC resize flow (orphan-delete of the StatefulSet, per-pod PVC replacement, interaction with the OnDelete controller) will be covered in a separate proposal.
lets not mention the extra details which is not decided yet, may be just mention the issue no. https://github.com/gardener/etcd-druid/issues/481 to follow.

2026-04-23 17:17 UTC, ishan16696 commented on docs/proposals/06-sts-ondelete-strategy.md
> +| Second | Leader | Deleting the leader triggers an election, so it is done last. |
I think we may not need it as I found on graceful deletion(shutdown) of a leader, etcd leader itself try to transfer the leadership before stoping the server.
https://github.com/etcd-io/etcd/blob/326d5a2e7765d1d918865d2c3897f0a27320db80/server/etcdserver/server.go#L1319-L1331

2026-04-23 18:50 UTC, shreyas-s-rao commented on docs/proposals/07-sts-ondelete-strategy.md
> +For a single-node etcd cluster, both `RollingUpdate` and `OnDelete` produce the same outcome since there is only one pod to update. The benefit of `OnDelete` is specific to multi-node clusters where
For single-node it doesn't make much of a difference. But we can avoid the switching between update strategies when scale-up happens. And of course, if the Etcd spec says "replicas:1, updateStrategy: OnDelete`, then druid must respect that and set it in the sts spec accordingly.

2026-05-04 13:48 UTC, vlerenc commented on docs/proposals/06-sts-ondelete-strategy.md
> +> Note: The `controller-revision-hash` is computed from the pod template spec only. Changes to `volumeClaimTemplates` do not affect this hash. See [Interaction with PVC Resizing](#interaction-with-pv
That's an internal implementation detail that may change. Unlikely, but possible, right? If that's indeed not a binding/public API contract, let's acknowledge that here with a sentence?

2026-05-04 13:48 UTC, vlerenc commented on docs/proposals/07-sts-ondelete-strategy.md
> +The controller processes one pod per reconciliation cycle. After updating a pod, it requeues and waits for the pod to come back before proceeding to the next one. This ensures that the cluster is nev
What happens if a pod never comes back (Resource exhaustion, PV stuck in Pending, scheduling constraints? Should the proposal define: (1) a timeout after which the controller gives up or escalates, (2) whether exponential backoff is applied to requeue intervals, and (3) how the stuck state is surfaced, e.g., condition, event, metric (weekest). Without this, a single stuck pod blocks all further updates indefinitely, right?

2026-05-04 13:48 UTC, vlerenc commented on docs/proposals/06-sts-ondelete-strategy.md
> +- The update process may span multiple reconciliation cycles (waiting for pods to come back, checking health, proceeding to the next pod). Embedding this in the StatefulSet component would make it a
Indeed, what coordinates these two controllers when acting on the same StatefulSet concurrently? If the Etcd reconciler pushes a new STS pod template (new updateRevision) while the OnDelete controller is mid-rollout of the previous revision, what happens? I expect the OnDelete controller re-evaluates all pods against the latest revision, effectively restarting its procedure, but this should be stated explicitly, especially regarding potential update conflicts on the STS object itself.

2026-05-05 10:30 UTC, anveshreddy18 commented on docs/proposals/07-sts-ondelete-strategy.md
> +- **Non-participating pod**: A pod whose etcd container is not part of the quorum (the member may be down, restarting, or not yet joined).
I agree with the cases you mentioned, but from the perspective of ondelete controller whose job is to update the pods in a reasonable manner - need not get into the complexities of why a member is down, that opens up a lot of complexity. I feel it's much simpler and correct to let the ondelete do it's work based on the state it observes and if it fixes the problem, all good. But if not due to permanent quorum loss, that anyway requires manual intervention as you mentioned - this was the case previously as well. So The `participating` and `non-participating` distinction helps simplify the proposal by defining a clear process on which one gets deleted when. If you feel the name itself is a bit confusing, I'm open to change that if you have a better recommendation.

2026-05-05 10:35 UTC, anveshreddy18 commented on docs/proposals/06-sts-ondelete-strategy.md
> +The StatefulSet controller starts from Pod N (the highest ordinal), terminates it, and waits for the new pod to become ready. If the terminated pod is not the originally unhealthy one, quorum is lost
Yes, it'll be transient quorum loss. Will mention that clearly.

2026-05-05 10:37 UTC, anveshreddy18 commented on docs/proposals/07-sts-ondelete-strategy.md
> +For a single-node etcd cluster, both `RollingUpdate` and `OnDelete` produce the same outcome since there is only one pod to update. The benefit of `OnDelete` is specific to multi-node clusters where
> if the Etcd spec says "replicas:1, updateStrategy: OnDelete`, then druid must respect that and set it in the sts spec accordingly.

I agree with this, while what Ishan mentioned is correct that there's no effect but I feel we should respect the user decision on what they want, not obeying it actually makes it more complicated imo.

2026-05-05 10:43 UTC, anveshreddy18 commented on docs/proposals/06-sts-ondelete-strategy.md
> +- **Default value**: `OnDelete`
If your concern is that `OnDelete` might need some testing in the landscapes before we go all-in, I agree with that - we can make the default `RollingUpdate` and move to `OnDelete` once we're confident about it.

But just curious, I didn't quite understand the below line
>to not break the current behaviour?

OnDelete vs RollingUpdate is an internal implementation change which doesn't affect the end state right? it only affects how it reaches that end state, from that perspective I don't think it makes much difference if we do it right away or after a few releases.

Pls correct me if you mean something else or I didn't understand it right. But I'll change that to `RollingUpdate` to allow selective testing of `OnDelete` on some seeds initially.

2026-05-05 10:48 UTC, anveshreddy18 commented on docs/proposals/06-sts-ondelete-strategy.md
> +The decision to use a spec field instead of a feature gate is documented in [Decision Record 003](../decisions/003-ondelete-as-spec-field-not-feature-gate.md). The key reasons are: per-cluster contro
oops, that's an internal backlog record that I misplaced here, do you think the decision record is useful in the context of this proposal too? I recorded it mainly for internal alignment. Pls lmk wdyt of this.

2026-05-05 11:00 UTC, anveshreddy18 commented on docs/proposals/06-sts-ondelete-strategy.md
> +- The update process may span multiple reconciliation cycles (waiting for pods to come back, checking health, proceeding to the next pod). Embedding this in the StatefulSet component would make it a
> Does having two controllers lead to any possible race conditions?

As STS controller allows only one strategy at the same time, it's purely an implementation specific on how we manage the state interally, a correct implementation of enabling and disabling ondelete controller only after STS updatestrategy is set to `OnDelete` and before STS updatestrategy is set to `RollingUpdate` respectively will be sufficient and won't lead to any race conditions.

> I expect the OnDelete controller re-evaluates all pods against the latest revision

Right, it evaluates basis on the latest updateRevision and now the previously updated pods will be again in-queue, so ondelete controller handles it well as it's stateless and always tries to be on the latest version + pick members in right order.

I'll address the conflict concern about two controllers acting simultaneously in the proposal.

2026-05-05 11:02 UTC, anveshreddy18 commented on docs/proposals/06-sts-ondelete-strategy.md
> +> Note: The `controller-revision-hash` is computed from the pod template spec only. Changes to `volumeClaimTemplates` do not affect this hash. See [Interaction with PVC Resizing](#interaction-with-pv
> Unlikely, but possible, right?

Right, it can change. I'll mention that here.

2026-05-05 12:47 UTC, anveshreddy18 commented on docs/proposals/07-sts-ondelete-strategy.md
> +**Switching from RollingUpdate to OnDelete:**
Yes exactly as you assumed, switching between strategies is seamless as both the controllers  ( ondelete & even sts controller too ) check controller revision hash and update revision to decide, so that's not a concern for us.

2026-05-05 17:08 UTC, shreyas-s-rao commented
@anveshreddy18 looks like the statefulset currentRevision issue was fixed by https://github.com/kubernetes/kubernetes/pull/136833. please check and update the DEP accordingly.

2026-05-05 18:42 UTC, anveshreddy18 commented on docs/proposals/06-sts-ondelete-strategy.md
> +| Second | Leader | Deleting the leader triggers an election, so it is done last. |
Yes, the extra step of moving the leader is not needed.

2026-05-05 18:52 UTC, anveshreddy18 commented on docs/proposals/07-sts-ondelete-strategy.md
> +**Switching from RollingUpdate to OnDelete:**
Yeah you're right - take an edge case - if the rolling update was stuck because it was waiting for an `updated pod` to come up, then when ondelete takes over it also waits on the same pod to come up, that behaviour remains intact, the main place where ondelete & rollingupdate differ is in the order of selection.

2026-05-05 18:57 UTC, anveshreddy18 commented on docs/proposals/07-sts-ondelete-strategy.md
> +**Switching from OnDelete to RollingUpdate:**
In this case the rolling update strategy as performed by sts controller will update only the remainig 2 pods, I've tested this behaviour in poc and it works as expected because sts controller also checks the same `controller-revision-hash` and sts updateRevision to decide which all pods need to be updated, so they're consistent in that.

2026-05-05 18:57 UTC, anveshreddy18 commented on docs/proposals/06-sts-ondelete-strategy.md
> +### VPA and HVPA Interaction
yea, will remove that. Thanks for flagging.

2026-05-05 19:00 UTC, anveshreddy18 commented on docs/proposals/06-sts-ondelete-strategy.md
> +The details of the PVC resize flow (orphan-delete of the StatefulSet, per-pod PVC replacement, interaction with the OnDelete controller) will be covered in a separate proposal.
> just mention the issue

Sure, will do that.

> not mention the extra details 

Which extra details do you mean here? These -> `(orphan-delete of the StatefulSet, per-pod PVC replacement, interaction with the OnDelete controller)` ? I can remove them from this proposal but added just to give some context.

2026-05-06 06:04 UTC, anveshreddy18 commented on docs/proposals/assets/06-rolling-update-state-diagram.png
I lost the .excalidraw file for this previously :( .... can we live with this small miss for now as otherwise I'd have to reconstruct the diagram again. Wdyt?

2026-05-06 06:06 UTC, anveshreddy18 commented on docs/proposals/06-sts-ondelete-strategy.md
> +The controller processes one pod per reconciliation cycle. After updating a pod, it requeues and waits for the pod to come back before proceeding to the next one. This ensures that the cluster is nev
True, but can we consider that a benefit though? Isn't it considered a standard practice in controller design to requeue instead of blocking threads? If you feel it strongly, I can add that.

2026-05-06 06:07 UTC, anveshreddy18 commented on docs/proposals/assets/07-OnDelete-StateDiagram.png
Thanks 🙇

2026-05-06 06:08 UTC, anveshreddy18 commented on docs/proposals/06-sts-ondelete-strategy.md
> +  <img src="assets/06-OnDelete-StateDiagram-With-Etcdbr-Health.png" alt="OnDelete state diagram with backup-restore health awareness (future scope)" width="700">
Okay, I'll remove the embedding from the proposal but keep the diagram in assets for future use. I hope that's fine.

2026-05-06 06:18 UTC, anveshreddy18 commented on docs/proposals/07-sts-ondelete-strategy.md
> +- **Non-participating pod**: A pod whose etcd container is not part of the quorum (the member may be down, restarting, or not yet joined).
> A member may be restarting, but would still be part of the quorum right?

While the cluster can still have quorum, but this restarting member is not contributing to that quorum, correct? A member can not be part of quorum because of two reasons 1) it's readiness probe call is unanswered due to etcd container having internal problems leading to crashes, etc 2) it's readiness probe call is answered and is failing, in this case it's because the cluster lost quorum, so we cannot say that this pod is contributing to quorum when quorum itself is not a reality in that moment.

So effectively by `non-participating` here, I mean that the corresponding etcd container's contribution to the quorum is nil, not about whether the cluster is quorate or not.

Pls lmk if it's still unclear, we can have an internal discussion :)

2026-05-06 06:24 UTC, anveshreddy18 commented on docs/proposals/07-sts-ondelete-strategy.md
> +The controller processes one pod per reconciliation cycle. After updating a pod, it requeues and waits for the pod to come back before proceeding to the next one. This ensures that the cluster is nev
> Without this, a single stuck pod blocks all further updates indefinitely, right?

Yes, I did think about this and left it to be retried indefinitely, but you raise a valid suggestion - `a timeout after which the controller gives up or escalates` -- I think escalating is appropriate here, we can have it as a condition on the Etcd and dashboard can surface the error if and when an update is stuck for a long time ( as defined by a timeout ), then a manual intervention from etcd team might be the best course of action.

What do you think @shreyas-s-rao @ishan16696

2026-05-07 04:17 UTC, shreyas-s-rao commented on docs/proposals/07-sts-ondelete-strategy.md
> +The controller processes one pod per reconciliation cycle. After updating a pod, it requeues and waits for the pod to come back before proceeding to the next one. This ensures that the cluster is nev
The same issue is applicable for regular rolling update by statefulset controller too today - if a pod gets stuck and doesn't come up, the rolling will not continue. But since the pod update when using `OnDelete` strategy is in druid's control, druid can emit metrics and we can configure alerts for such cases. I would not expect druid itself to perform any remediations in such cases since the pod can get stuck for multiple reasons and druid cannot be ready to handle every such case.

2026-05-07 04:19 UTC, shreyas-s-rao commented on docs/proposals/06-sts-ondelete-strategy.md
> +The details of the PVC resize flow (orphan-delete of the StatefulSet, per-pod PVC replacement, interaction with the OnDelete controller) will be covered in a separate proposal.
I think mentioning about PVC resize just confuses readers since this DEP is mainly about OnDelete and has nothing to do with PVC resizing (although we had previously discussed both together, but then decided/realised that they are not dependent on each other and can be decoupled).

2026-05-07 04:27 UTC, shreyas-s-rao commented on docs/proposals/06-sts-ondelete-strategy.md
> +- **Non-participating pod**: A pod whose etcd container is not part of the quorum (the member may be down, restarting, or not yet joined).
Ok, so to understand correctly, a participating pod means it's actively part of the current quorum right? Ex: 3-member cluster with a learner still learning before joining, and one of the followers is currently restarting:
- leader is `participating`
- one follower is `participating`
- one follower (the one that's restarting) is `non-participating`
- learner is `non-participating`

Is my understanding correct?

2026-05-07 04:27 UTC, shreyas-s-rao commented on docs/proposals/assets/07-rolling-update-state-diagram.png
Ok, fine for now

2026-05-07 04:28 UTC, shreyas-s-rao commented on docs/proposals/06-sts-ondelete-strategy.md
> +- **Default value**: `OnDelete`
Since OnDelete is a new feature, we should ideally not make it the default behavior until it's well-tested in production. Hence, it should be an opt-in feature for now.

2026-05-07 04:29 UTC, shreyas-s-rao commented on docs/proposals/06-sts-ondelete-strategy.md
> +The decision to use a spec field instead of a feature gate is documented in [Decision Record 003](../decisions/003-ondelete-as-spec-field-not-feature-gate.md). The key reasons are: per-cluster contro
if it's internal, then it should not be mentioned in the DEP which is a public-facing doc.

2026-05-07 04:36 UTC, shreyas-s-rao commented on docs/proposals/07-sts-ondelete-strategy.md
> +The controller processes one pod per reconciliation cycle. After updating a pod, it requeues and waits for the pod to come back before proceeding to the next one. This ensures that the cluster is nev
Since you were mentioning the benefits, I thought this could be added as well, just to be explicit.

2026-05-07 04:36 UTC, shreyas-s-rao commented on docs/proposals/06-sts-ondelete-strategy.md
> +| Second | Leader | Deleting the leader triggers an election, so it is done last. |
Ok, if this is the case, then ignore my comment.

2026-05-07 05:28 UTC, anveshreddy18 commented on docs/proposals/06-sts-ondelete-strategy.md
> +- **Default value**: `OnDelete`
Agreed! have made the changes my previous commit for this.

2026-05-07 05:29 UTC, anveshreddy18 commented on docs/proposals/06-sts-ondelete-strategy.md
> +The decision to use a spec field instead of a feature gate is documented in [Decision Record 003](../decisions/003-ondelete-as-spec-field-not-feature-gate.md). The key reasons are: per-cluster contro
yeah but I meant whether making it public and referring in the DEP makes sense? But I think it's better to just remove this ref, will do that.

2026-05-07 05:33 UTC, anveshreddy18 commented on docs/proposals/06-sts-ondelete-strategy.md
> +The details of the PVC resize flow (orphan-delete of the StatefulSet, per-pod PVC replacement, interaction with the OnDelete controller) will be covered in a separate proposal.
I just wanted to address the PVC resize usecase also as it should not look like we've not thought about PVC resizing in the context of this DEP.

I removed the explicit details and mentioned the issue as Ishan suggested, I hope that's alright.

2026-05-07 05:41 UTC, anveshreddy18 commented on docs/proposals/07-sts-ondelete-strategy.md
> +- **Non-participating pod**: A pod whose etcd container is not part of the quorum (the member may be down, restarting, or not yet joined).
are you referring to a 4-member etcd cluster ( 3 prev + 1 new learner)? In that case quorum would be 3, and since two etcd containers are not contributing to the quorum, the entire quorum is now lost... so no one is now participating in the quorum ( because it doesn't exist ).

But in the same case if the followers were not restarting - then we have 3 for quorum, so it looks like below:

- leader is `participating`
- two followers are `participating`
- learner is `non-participating`

Or did I not understand your question properly?

2026-05-07 05:43 UTC, anveshreddy18 commented on docs/proposals/06-sts-ondelete-strategy.md
> +The controller processes one pod per reconciliation cycle. After updating a pod, it requeues and waits for the pod to come back before proceeding to the next one. This ensures that the cluster is nev
Sure, we can add that. Will resolve this comment once I add it together with other changes requested by other reviewers once they respond.

2026-05-07 07:46 UTC, shreyas-s-rao commented on docs/proposals/07-sts-ondelete-strategy.md
> +- **Non-participating pod**: A pod whose etcd container is not part of the quorum (the member may be down, restarting, or not yet joined).
Assume the case of live CPM where 3-member cluster is scaled to 5 members (3 -> 4 -> 5). So during the time when etcd.spec.replicas=4, the cluster has 3 voting members and one learner yet to join. That's the case I'm talking about, where the cluster has 1 leader, 2 followers, and one learner. Until the learner joins, the number of voting members in the cluster would be 3, and hence the quorum requirement would be 2.

2026-05-07 07:47 UTC, shreyas-s-rao commented on docs/proposals/06-sts-ondelete-strategy.md
> +The decision to use a spec field instead of a feature gate is documented in [Decision Record 003](../decisions/003-ondelete-as-spec-field-not-feature-gate.md). The key reasons are: per-cluster contro
Yes, removing this ref is better.

2026-05-12 05:45 UTC, ishan16696 commented on docs/proposals/06-sts-ondelete-strategy.md
> +The details of the PVC resize flow (orphan-delete of the StatefulSet, per-pod PVC replacement, interaction with the OnDelete controller) will be covered in a separate proposal.
ok, thanks .. I will check

2026-05-12 05:53 UTC, ishan16696 commented on docs/proposals/06-sts-ondelete-strategy.md
> +The StatefulSet controller starts from Pod N (the highest ordinal), terminates it, and waits for the new pod to become ready. If the terminated pod is not the originally unhealthy one, quorum is lost
yeah, may be wording here can be improve, mention that "it can lead to transient quorum loss" or "temp. down time".

2026-05-12 09:34 UTC, anveshreddy18 commented on docs/proposals/06-sts-ondelete-strategy.md
> +The StatefulSet controller starts from Pod N (the highest ordinal), terminates it, and waits for the new pod to become ready. If the terminated pod is not the originally unhealthy one, quorum is lost
yes I've updated it already, missed mentioning that in this conversation.

2026-05-12 09:36 UTC, anveshreddy18 commented
/hold
to not accidentally merge when an approver lgtm's as others might want to review the DEP too.

2026-05-12 09:41 UTC, anveshreddy18 commented on docs/proposals/07-sts-ondelete-strategy.md
> +- **Non-participating pod**: A pod whose etcd container is not part of the quorum (the member may be down, restarting, or not yet joined).
In this case what you said in this comment https://github.com/gardener/etcd-druid/pull/879#discussion_r3198947302 is right. 

More specifically this :
> a participating pod means it's actively part of the current quorum right?

The member has to be healthy first for it to be an active participant in the quorum, so a restarting member is consiered `non-participating`.

2026-05-12 10:04 UTC, anveshreddy18 commented on docs/proposals/07-sts-ondelete-strategy.md
> +The controller processes one pod per reconciliation cycle. After updating a pod, it requeues and waits for the pod to come back before proceeding to the next one. This ensures that the cluster is nev
I just realised that it's already covered at https://github.com/anveshreddy18/etcd-druid/blob/d2ca76bdd9b608bf3ec0725594983bd8e94deed8/docs/proposals/06-sts-ondelete-strategy.md?plain=1#L86. So I guess we don't need it again here.

2026-05-12 11:03 UTC, ishan16696 commented on docs/proposals/07-sts-ondelete-strategy.md
> +- `etcddruid_ondelete_update_duration_seconds`: Time from the first detection of an `updateRevision` change to the completion of all pod updates. Labeled by etcd cluster name.
Isn't it should also have `etcd member name` or `pod-name` also as a label, so that we can determine which member took long time to come up and which member was picked up first. wdyt ?

2026-05-12 11:03 UTC, ishan16696 commented on docs/proposals/07-sts-ondelete-strategy.md
> +- **Non-participating pod**: A pod whose etcd container is not part of the quorum (the member may be down, restarting, or not yet joined).
my point was, this state: "non-participating" is very transient state (~99% times apart from  ~1-2% volume attach-deattach issue), should on-delete controller make a decision on basis of state which is very transient in nature or it can simply waits for this "non-participating" to become "participating" then start its algorithm of picking it, isn't that will simplify lot of things ?

2026-05-12 11:19 UTC, shreyas-s-rao commented on docs/proposals/07-sts-ondelete-strategy.md
> +- **Non-participating pod**: A pod whose etcd container is not part of the quorum (the member may be down, restarting, or not yet joined).
Understood, thanks

2026-05-12 11:20 UTC, shreyas-s-rao approved these changes
@anveshreddy18 thanks for addressing my comments.
/lgtm

2026-05-12 12:38 UTC, ishan16696 requested changes
few doubts:

2026-05-12 12:38 UTC, ishan16696 commented on docs/proposals/06-sts-ondelete-strategy.md
> +The OnDelete controller is stateless: i.e every reconciliation re-reads the current `.status.updateRevision` and the current pod set. If the Etcd reconciler pushes a new pod template while OnDelete i
```suggestion
The OnDelete controller is stateless: i.e every reconciliation re-reads the current StatefulSet's `.status.updateRevision` and the current pod set. If the Etcd reconciler pushes a new pod template while OnDelete is mid-rollout of a prior revision, the next reconciliation observes the new `updateRevision`, treats every pod whose `controller-revision-hash` no longer matches as outdated (including ones already updated against the prior revision), and continues the procedure from there. No explicit handover between controllers is needed.
```

2026-05-12 12:38 UTC, ishan16696 commented on docs/proposals/07-quorum-aware-pod-updates.md
> +### Safeguarding Etcd Pods from Voluntary Disruptions
Do we need this extra info. in this DEP as it's not related, may you can mention this in some other relevant doc. wdyt ?

2026-05-12 12:38 UTC, ishan16696 commented on docs/proposals/07-quorum-aware-pod-updates.md
> +The controller determines member roles by reading the member lease's `holderIdentity` field, which contains the member ID and role.
If on-delete controller require `member leases` then `onDelete` strategy will not work for self hosted clusters. Although things aren't finalize for self hosted clusters, so I'm also not sure how to make `onDelete` work for self hosted or do we even need a `onDelete` strategy for self hosted.
/cc @CaptainIRS

2026-05-12 12:43 UTC, anveshreddy18 commented on docs/proposals/07-sts-ondelete-strategy.md
> +- `etcddruid_ondelete_update_duration_seconds`: Time from the first detection of an `updateRevision` change to the completion of all pod updates. Labeled by etcd cluster name.
You're right Ishan but I think those will be considered implementation details, so didn't add too many details here. Just the metric and what it does is mentioned.

2026-05-12 12:47 UTC, anveshreddy18 commented on docs/proposals/07-sts-ondelete-strategy.md
> +- **Non-participating pod**: A pod whose etcd container is not part of the quorum (the member may be down, restarting, or not yet joined).
I get your concern but imo the purpose of the ondelete controller should always be to progress the updates in the best way "possible", we can make many tiny improvements but then we would be diverging from our original problem statement. 

If at the time of the rolling, a pod is not actively participating in the quorum for any reason is treated the same as I believe ondelete controller shouldn't bother too much about what kind of issue it is, that is for us/operators to decide if the update process is stuck due to permanent quorum loss or anything. Wdyt?

2026-05-12 12:51 UTC, anveshreddy18 commented on docs/proposals/07-quorum-aware-pod-updates.md
> +### Safeguarding Etcd Pods from Voluntary Disruptions
It's one of the important factors in driving our decisions of the proposal, so I thought to mention it as without that we would be proposing something but when people are reading they might not understand why we're proposing something... So imo it acts as a necessary information to justify the actions the proposal takes.

2026-05-12 12:53 UTC, anveshreddy18 commented on docs/proposals/07-quorum-aware-pod-updates.md
> +The controller determines member roles by reading the member lease's `holderIdentity` field, which contains the member ID and role.
In self-hosted clusters the sts spec.replicas will be `0`, so there's no difference between `OnDelete` or `RollingUpdate` there as we won't be rolling the pods. A static pod translator will pickup the pod template spec from sts and provide the pods.

In this I think we're fine? Pls lmk if my understanding is incorrect @CaptainIRS.

2026-05-13 02:57 UTC, ishan16696 commented on docs/proposals/07-sts-ondelete-strategy.md
> +- `etcddruid_ondelete_update_duration_seconds`: Time from the first detection of an `updateRevision` change to the completion of all pod updates. Labeled by etcd cluster name.
>Labeled by etcd cluster name.

I think you have mentioned the labelling, hence I commented.

2026-05-13 03:06 UTC, ishan16696 commented on docs/proposals/07-quorum-aware-pod-updates.md
> +### Safeguarding Etcd Pods from Voluntary Disruptions
ok, if you feel it should be mentioned then it's fine ... no strong opinion on this.

2026-05-13 04:04 UTC, ishan16696 commented on docs/proposals/07-sts-ondelete-strategy.md
> +The controller processes one pod per reconciliation cycle. After updating a pod, it requeues and waits for the pod to come back before proceeding to the next one. This ensures that the cluster is nev
I agree with shreyas here but I wouldn't like to configure a alert for such cases because if one of etcd pod becomes `not ready` then etcd resource status is already capturing that and it will get reflected in gardener dashboard. From on-delete controller perspective a exponential retry is seems to be a good option to me.

2026-05-13 04:23 UTC, ishan16696 commented on docs/proposals/07-sts-ondelete-strategy.md
> +- **Non-participating pod**: A pod whose etcd container is not part of the quorum (the member may be down, restarting, or not yet joined).
ok, if you feel that's necessary then its fine. Now I just wanted to know one more thing, Will there be any threshold time to declare a member is in "non-participating" state or controller just check the readiness of member once and declare that member a "non-participating" ?

2026-05-13 04:34 UTC, CaptainIRS commented on docs/proposals/07-quorum-aware-pod-updates.md
> +The controller determines member roles by reading the member lease's `holderIdentity` field, which contains the member ID and role.
@anveshreddy18 you're right. The pod updates would not be the responsibility of etcd-druid in that case.

2026-05-13 07:12 UTC, anveshreddy18 commented on docs/proposals/07-sts-ondelete-strategy.md
> +- `etcddruid_ondelete_update_duration_seconds`: Time from the first detection of an `updateRevision` change to the completion of all pod updates. Labeled by etcd cluster name.
My bad, I'll remove that. But these 2 metrics are cluster wide hence the label name was cluster name - to determine which member took how much time, I feel we need to introduce a different metric for that altogether, wdyt?

2026-05-13 07:22 UTC, anveshreddy18 commented on docs/proposals/07-sts-ondelete-strategy.md
> +- **Non-participating pod**: A pod whose etcd container is not part of the quorum (the member may be down, restarting, or not yet joined).
I'm thinking to not introduce any threshold time for 2 reasons:
1. the pod update process is meant to be a very short process and every pod has to go through the update, so adding extra wait time and then anyway eventually deleting them will not much difference - now let's say the ondelete controller picks a pod for reconciling in this reconcile loop, then it means all other pods which were more damaged already was updated, and it came to this only after them - now if let say we wait for some threshold time to see if this pod becomes healthy, it will still become a follower and we'll pick that up again to update -- so anyway in both cases that pod becomes our target for updation, so I would rather proceed than introducing some wait.
2. we don't precisely know how much time to wait for, we will have to choose a magic number and even then we can pick to update a pod that's only in transient quorum loss.

Wdyt?

2026-05-13 07:27 UTC, anveshreddy18 commented on docs/proposals/07-sts-ondelete-strategy.md
> +The controller processes one pod per reconciliation cycle. After updating a pod, it requeues and waits for the pod to come back before proceeding to the next one. This ensures that the cluster is nev
I agree with both of you, I think we just need to do a exponential retry when we're waiting for a pod to become ready after the update as @ishan16696 mentioned, that'd be the most appropriate concern for the ondelete controller imo.

2026-05-13 09:38 UTC, ishan16696 commented on docs/proposals/07-sts-ondelete-strategy.md
> +- `etcddruid_ondelete_update_duration_seconds`: Time from the first detection of an `updateRevision` change to the completion of all pod updates. Labeled by etcd cluster name.
> hence the label name was cluster name 

are you referring to shoot-namespace .. right ? not clusterName

2026-05-13 10:01 UTC, ishan16696 commented on docs/proposals/07-sts-ondelete-strategy.md
> +- **Non-participating pod**: A pod whose etcd container is not part of the quorum (the member may be down, restarting, or not yet joined).
ok, fine

2026-05-13 11:13 UTC, CaptainIRS requested changes
Hi @anveshreddy18, thanks for raising the DEP! I have added a few comments. PTAL, thanks.

2026-05-13 11:13 UTC, CaptainIRS commented on docs/proposals/07-sts-ondelete-strategy.md
> +Consider a 3-member etcd cluster with pods `P-0`, `P-1`, and `P-2`. If `P-0` becomes unhealthy (due to network issues, node failure, or an internal error), the cluster still has quorum with `P-1` and
I'm not really sure whether this should be the primary motivation though. I think this is a rare case which could partially be solved with OnDelete strategy. I wonder if a more general improvement due to OnDelete strategy like "optimizing the number of leader moves during an update" could be quoted as the primary motivation instead.

Explanation for why I think this is a rare case and why I think it is only partially solved by OnDelete:
1. Operationally we haven't observed this case of the StatefulSet update coinciding with a cluster state where a pod was already unhealthy. This could mean either of these things:
    * The coincidence has never occurred in the past.
    * The coincidence has occurred, but it was brief and transient enough to not set off any alarms for us to notice.
2. We assume that a restart of the unhealthy pod would resolve the issue with the pod. In which case, I'm not sure there are many classes of issues where a container restart (which Kubernetes already does) could not resolve, but a pod restart could resolve without manual intervention. It would be ideal if some practical example could be mentioned for this case to motivate the point.
3. The mentioned causes of the unhealthy pod like node failure could also cause transient quorum loss during an update with OnDelete strategy (Cases like the OnDelete controller triggers a pod deletion and before the pod becomes ready the node behind another pod fails). So, we're only solving a specific subset of cases.

2026-05-13 11:13 UTC, CaptainIRS commented on docs/proposals/06-sts-ondelete-strategy.md
> +> **Note:** The `controller-revision-hash` is an internal contract of the Kubernetes StatefulSet controller rather than a documented public API. Changes to its semantics are unlikely but possible; if
I think we shouldn't mention the string `controller-revision-hash` in the DEP. `appsv1.StatefulSetRevisionLabel` is part of the public API. So, I think as long as we're relying on this, we're safe.

2026-05-13 11:13 UTC, CaptainIRS commented on docs/proposals/07-quorum-aware-pod-updates.md
> +The controller determines member roles by reading the member lease's `holderIdentity` field, which contains the member ID and role.
Could we instead rely on the `status.members` field? This way we could easily swap out the implementation of how status is populated if we wish to later without affecting the OnDelete controller.

2026-05-13 11:13 UTC, CaptainIRS commented on docs/proposals/07-sts-ondelete-strategy.md
> +The default is set to `RollingUpdate` to preserve the existing behaviour for current clusters; `OnDelete` is opt-in initially so it can be exercised on selected clusters. Once `OnDelete` has been val
I'm not sure I understand this fully. Since the default for the field will be `RollingUpdate` for a few releases, the `etcd-druid` instances that are running will pick this up and persist this default in the `Etcd` objects they're managing. In a future release, even if the default changes, those `Etcd` objects that were persisted earlier would still be applicable unless the user explicitly sets the field to `OnDelete`. I wonder if this is the expected behaviour.

2026-05-13 11:13 UTC, CaptainIRS commented on docs/proposals/06-sts-ondelete-strategy.md
> +| Second | etcd process is alive but readiness fails (quorum loss) | Process is healthy. Restarting it gets the new spec without making things worse. |
Nit:
```suggestion
| First | etcd process is dead (CrashLoopBackOff, Error, not running) | Already broken. Restarting the pod may fix the issue. |
| Second | etcd process is alive but readiness fails (quorum loss) | Process is healthy. Restarting the pod gets the new spec without making things worse. |
```
Since the restart is happening at the pod level even though the trigger is at the container level.

2026-05-13 11:13 UTC, CaptainIRS commented on docs/proposals/06-sts-ondelete-strategy.md
> +| First | etcd process is dead (CrashLoopBackOff, Error, not running) | Already broken. Restarting it may fix the issue. |
Could we be explicit about the statuses under which this priority is assigned? Does "not running" include cases like the container in "Waiting" for example? Also https://github.com/gardener/etcd-druid/pull/879#discussion_r3233063344 applies

2026-05-13 11:13 UTC, CaptainIRS commented on docs/proposals/07-sts-ondelete-strategy.md
> +1. **Is the pod participating in the etcd quorum?** This is determined by the etcd container's readiness. The readiness probe hits etcd-wrapper's `/readyz` endpoint, which performs an etcd client `Ge
Just a thought: would we be allowing updates during phases like a scale-up? For instance if we're scaling from 1 to 3. During the scale up when the etcd member is a learner, I wonder what the `/readyz` response would be, since a learner should be able to service a linearizable `Get` request. So, it might not be right to assume that it is participating in quorum in that case. Feel free to correct me if I'm wrong.

2026-05-13 11:13 UTC, CaptainIRS commented on docs/proposals/07-sts-ondelete-strategy.md
> +   The controller determines local process liveness by inspecting the pod's container status from the Kubernetes API. If the etcd container is in `CrashLoopBackOff`, `Error`, or is not running, the p
I think `CrashLoopBackOff`/`Error` are pod-level statuses and not container-level ones from what I understand from https://kubernetes.io/docs/concepts/workloads/pods/pod-lifecycle/#container-states. Unless you're referring to other mechanisms of determining the container status.

2026-05-13 11:13 UTC, CaptainIRS commented on docs/proposals/07-sts-ondelete-strategy.md
> +**Step 2: Check for non-participating pods that need updating.** If any outdated pod is non-participating, select one for deletion using the following sub-priority:
As mentioned by @ishan16696 in https://github.com/gardener/etcd-druid/pull/879#discussion_r3231484677, if we don't have a time threshold for classifying a pod as non-participating (or have some other mechanism), could there be cases where we end up misclassifying the pod? For example, let's say the OnDemand controller picked a pod for deletion and issued a delete call to an etcd pod. In the next reconciliation, if the pod wasn't deleted and recreated by that time, it might be classified as non-participating pod that needs updating, which I'm not sure is intended.

2026-05-13 11:13 UTC, CaptainIRS commented on docs/proposals/06-sts-ondelete-strategy.md
> +Delete the selected pod and requeue. Wait for it to come back before proceeding to the next.
I think `Wait for it to come back before proceeding to the next.` could be a separate step at the start of the reconciliation procedure. Since the controller is stateless, I wonder what the approach would be to make sure we pick the pod we just deleted recently to wait for. Or is it a general `AllMembersReady` kind of wait?

2026-05-13 11:13 UTC, CaptainIRS commented on docs/proposals/06-sts-ondelete-strategy.md
> +- The theoretical race condition (an external actor disrupts a pod between the controller's health check and its delete call) is possible but rare in practice, and it exists equally with the current
I'm not sure I understand the benefits of `Delete` over the `Eviction` API w.r.t these 2 points. I think these 2 points are applicable regardless of the deletion approach though.

2026-05-13 11:13 UTC, CaptainIRS commented on docs/proposals/06-sts-ondelete-strategy.md
> +Before deleting the single pod, the controller should trigger an on-demand snapshot (if backup is configured) to ensure that the latest data is persisted. This is because the single-node cluster has
In this case, I think we need another step in the beginning of the reconciliation loop to requeue if an on-demand snapshot is in progress. WDYT? Also I think we need to consider what happens if the on-demand snapshot fails - do we proceed with the update, are retries to be setup, etc.

2026-05-13 11:13 UTC, CaptainIRS commented on docs/proposals/06-sts-ondelete-strategy.md
> +The Vertical Pod Autoscaler (VPA) does not modify the StatefulSet spec directly. VPA operates through two independent mechanisms:
Nit:
```suggestion
The Vertical Pod Autoscaler (VPA) in `Recreate` or `InPlaceOrRecreate` mode does not modify the StatefulSet spec directly. VPA operates through two independent mechanisms:
```
Just to avoid generalization based on defaults specific to Gardener.

2026-05-13 11:13 UTC, CaptainIRS commented on docs/proposals/06-sts-ondelete-strategy.md
> +The OnDelete controller detects outdated pods by comparing `controller-revision-hash` labels. This hash is computed from the pod template spec only and does not include `volumeClaimTemplates`. This m
If this is the case, if pod deletion has to be handled independent of the OnDelete logic, I think the point above this would not be valid. Since it is the responsibility of the PVC resizing flow to ensure quorum.

2026-05-13 11:13 UTC, CaptainIRS commented on docs/proposals/06-sts-ondelete-strategy.md
> +For these reasons, `OnDelete` with a health-aware controller provides a more robust solution for etcd clusters where quorum safety is critical.
I think both `OnDelete` and `maxUnavailable` are equivalent in terms of quorum safety. A fair point could be that with `OnDelete` we minimize the number of leadership transfers due to awareness about the member status.

2026-05-13 11:13 UTC, CaptainIRS commented on docs/proposals/07-sts-ondelete-strategy.md
> +- `etcddruid_ondelete_reconcile_cycles_total`: Number of reconciliation cycles required to complete a full pod update. Labeled by etcd cluster name.
I'm curious if it is feasible to calculate this delta for `etcddruid_ondelete_update_duration_seconds` since the controller is stateless and may not have the time of first detection (reconciliations can be separated by restarts of the controller). Unless there is another mechanism to derive the time of first detection. Same applies for the reconciliation cycles metric.

2026-05-13 11:21 UTC, anveshreddy18 commented on docs/proposals/07-sts-ondelete-strategy.md
> +- `etcddruid_ondelete_update_duration_seconds`: Time from the first detection of an `updateRevision` change to the completion of all pod updates. Labeled by etcd cluster name.
as discussed offline, we'll have both {namespace, name} labels for the metric, but will be omitting this info from the proposal as it falls under implementation details.

2026-05-13 11:28 UTC, CaptainIRS commented on docs/proposals/07-quorum-aware-pod-updates.md
> +The controller determines member roles by reading the member lease's `holderIdentity` field, which contains the member ID and role.
Also just to note (only relevant during implementation): we may need to check the time the information was updated to avoid depending on stale member information.

2026-05-13 11:58 UTC, anveshreddy18 commented on docs/proposals/07-sts-ondelete-strategy.md
> +Consider a 3-member etcd cluster with pods `P-0`, `P-1`, and `P-2`. If `P-0` becomes unhealthy (due to network issues, node failure, or an internal error), the cluster still has quorum with `P-1` and
Sorry I didn't get, the primary motivation was always about minimising transient quorum loss as opposed to optimising no.of leader moves as leader moves are anyway graceful as mentioned [here](https://github.com/etcd-io/etcd/blob/326d5a2e7765d1d918865d2c3897f0a27320db80/server/etcdserver/server.go#L1319-L1331). While I agree that the case I mentioned could be rare ( as we don't have the data to prove otherwise ) but the impact of that when it happens is what makes that case meaningful, and it's not like that's a theoretical problem as it can always happen anytime so I feel it's better to cover that as the motivation than quoting a marginal improvement with minimising no.of leader updates.

For 1.b):
I don't think that would've been the case always, we typically don't operate on the front line and miss a good no.of instances where a temporary quorum loss would've happened, out of them sometimes we'll get an RCA request but by the time we respond we could lose some data or the cluster owner would've moved ahead after creating the ticket, etc thereby the ticket becomes inconclusive - so the point is that even if it's a transient case ( we're mainly targetting transient issues though ) how much damage it can cause is the question and if we can prevent a good no.of them by updating the pod in question or by blocking the update process altogether, then I'd consider it a win over what we have.

for 2):
> We assume that a restart of the unhealthy pod would resolve the issue with the pod

Not necessarily, as I mentioned in the above point the main advantage of this is that we block the automated update process to investigate into why the unhealthy pod couldn't resolve after a restart and do manual operations on it rather than letting it go through and causing quorum loss ( in the case of rollingupdate ).

for 3):

Agreed. It's covered in the non-goals section that we don't have control over such infra issues, ondelete controller can only decide what to do based on the current state of the cluster and can't anticipate future issues like with node, etc; so imo it's actually right that it should proceed with the updates in this case and whatever happens after that's done is checked in the next reconciliation loop and it'll try to not damage the cluster state further. 

Wdyt?

2026-05-13 12:41 UTC, anveshreddy18 commented on docs/proposals/06-sts-ondelete-strategy.md
> +> **Note:** The `controller-revision-hash` is an internal contract of the Kubernetes StatefulSet controller rather than a documented public API. Changes to its semantics are unlikely but possible; if
Thanks for finding this, it'll definitely help to use this const over the string but (maybe by wording is wrong there) the main concern here is that the `controller-revision-hash` is populated in the Pod's `.metadata.labels.controller-revision-hash` and that's not guaranteed to be always populated this way, so I meant that could change and if that happens the comparison performed would need to be revisited.

2026-05-13 12:44 UTC, anveshreddy18 commented on docs/proposals/07-quorum-aware-pod-updates.md
> +The controller determines member roles by reading the member lease's `holderIdentity` field, which contains the member ID and role.
But wouldn't that introduce another layer of delay? Currently the lease itself could be updated with some delay, and the etcd status controller takes that info and populates the status conditions asynchronously to that, so now there'll be two delays added together and that could drift away the correctness of the ondelete algorithm in detecting follower/leader as quickly as possible compared to their original transition time.

2026-05-13 12:50 UTC, anveshreddy18 commented on docs/proposals/07-sts-ondelete-strategy.md
> +The default is set to `RollingUpdate` to preserve the existing behaviour for current clusters; `OnDelete` is opt-in initially so it can be exercised on selected clusters. Once `OnDelete` has been val
So we introduce a new `spec.updateStrategy` field (optional) for this - and the old `Etcd` objects that were persisted earlier will not have this field unless someone explicitly sets it to some strategy -> then etcd controller propagates that. But if they don't set any field, then the new druid release will default that to `OnDelete` thereby behaving as expected. Pls lmk if you have any questions.

2026-05-13 13:14 UTC, anveshreddy18 commented on docs/proposals/07-sts-ondelete-strategy.md
> +**Step 2: Check for non-participating pods that need updating.** If any outdated pod is non-participating, select one for deletion using the following sub-priority:
I addressed @ishan16696 's comment here: https://github.com/gardener/etcd-druid/pull/879#discussion_r3232276884.

> let's say the OnDemand controller picked a pod for deletion and issued a delete call to an etcd pod. In the next reconciliation, if the pod wasn't deleted and recreated by that time, it might be classified as non-participating pod that needs updating, which I'm not sure is intended.

Didn't understand what exactly is the issue, can you expand on this case a bit more? If I'm not wrong, I think the misunderstanding is that we do classification once for all the pods and stick with it across the reconciliations, but that's not how it's done as the classification is local to that particular reconciliation. Or is it something else? can you pls describe the issue in more detail.

2026-05-13 13:18 UTC, anveshreddy18 commented on docs/proposals/06-sts-ondelete-strategy.md
> +Delete the selected pod and requeue. Wait for it to come back before proceeding to the next.
It's more like `AreAllUpdatedMembersReady` condition that gets checked, the wording is just to keep the story narrow, but if you think it's confusing, then I can improve on that.

2026-05-13 13:21 UTC, anveshreddy18 commented on docs/proposals/06-sts-ondelete-strategy.md
> +For these reasons, `OnDelete` with a health-aware controller provides a more robust solution for etcd clusters where quorum safety is critical.
> I think both OnDelete and maxUnavailable are equivalent in terms of quorum safety.

Yeah, you're right.

> with OnDelete we minimize the number of leadership transfers due to awareness about the member status.

Not only that, the point above this also talks about update making progress vs getting stuck with ondelete vs maxUnavailable respectively.

2026-05-13 13:30 UTC, anveshreddy18 commented on docs/proposals/06-sts-ondelete-strategy.md
> +- The theoretical race condition (an external actor disrupts a pod between the controller's health check and its delete call) is possible but rare in practice, and it exists equally with the current
While the first point is generic, the second one differs for `Delete` vs `Eviction` and that point is actually a limitation and not a benefit. Why it matters is that if we use `Eviction` calls, then our eviction call in this scenario would be rejected whereas if we use the `Delete` call, it goes through, so there's a difference and this point talks about that mainly.

If you'd like me to reorganize the points to clear any confusion, I can do that.

2026-05-13 13:34 UTC, anveshreddy18 commented on docs/proposals/06-sts-ondelete-strategy.md
> +Before deleting the single pod, the controller should trigger an on-demand snapshot (if backup is configured) to ensure that the latest data is persisted. This is because the single-node cluster has
Actually now that I think more about it - it makes more sense to do it as part of Statefulset component `PreSync` independent of `OnDelete` or `RollingUpdate` flow as both do the same thing in a single-node case and both cases benefits from having a full snapshot taken before updates - but we can do that for image updates for now like how we did for etcd 3.5 upgrade, as doing for other pod template spec changes would require us to compute the hash diff, we can do that as well if the benefit to cost is justified. 

I think this decoupling will also allow the ondelete controller to not worry about snapshotting & stuff as well. Wdyt?

2026-05-14 03:43 UTC, CaptainIRS commented on docs/proposals/07-sts-ondelete-strategy.md
> +Consider a 3-member etcd cluster with pods `P-0`, `P-1`, and `P-2`. If `P-0` becomes unhealthy (due to network issues, node failure, or an internal error), the cluster still has quorum with `P-1` and
> if we can prevent a good no.of them by updating the pod in question or by blocking the update process altogether, then I'd consider it a win over what we have.

Okay, agreed.

>> We assume that a restart of the unhealthy pod would resolve the issue with the pod

> I mentioned in the above point the main advantage of this is that we block the automated update process to investigate into why the unhealthy pod couldn't resolve after a restart and do manual operations on it

I'm not sure I understand this. In the section for Alternatives, when talking about `maxUnavailable`, it is stated that 

"This approach has a key limitation: the StatefulSet controller waits for any unavailable pod to recover before proceeding. If a pod is already unhealthy and the update itself might fix it (for example, a configuration change or image bump), the controller is stuck waiting. The `OnDelete` strategy does not have this limitation because it can proactively delete the unhealthy pod first, potentially resolving the issue."

So, as I understand it the decision to use OnDelete instead of a simpler strategy like RollingUpdate + `maxUnavailable` hinges on the fact that we assume OnDelete strategy could potentially resolve the issue via a restart whereas the `maxAvailable` strategy would never be able to do so.

Essentially the premise behind the quoted statement from the Alternatives section is that there is a class of issues that a container restart (which Kubernetes already does) could not resolve, but a pod restart could resolve without manual intervention and that OnDelete would be able to help with this class of issues. My concern was about whether there are any issues you're aware of that fall into this class. Sorry, I didn't give enough context in the original comment. Feel free to correct me if my understanding is incorrect :)

2026-05-14 05:56 UTC, CaptainIRS commented on docs/proposals/07-sts-ondelete-strategy.md
> +The default is set to `RollingUpdate` to preserve the existing behaviour for current clusters; `OnDelete` is opt-in initially so it can be exercised on selected clusters. Once `OnDelete` has been val
Could you clarify on the API?

I see it as a `string` field in the proposal. So, I'm assuming you have defaults set using kubebuilder markers, so it would be added to the defaulting logic that executed during creation/updation of the CR.

Given the assumption, then consider this sequence of events (assume default is `RollingUpdate` initially):
1. User created CR omitting the `updateStrategy` field.
    * Now the defaulting logic sets `updateStrategy` as `RollingUpdate` and persists the `Etcd` object in storage.
2. We update druid with the new default value as `OnDelete`.
3. The user doesn't change the `updateStrategy` field (is omitted now as well) and triggers reconciliation.

In the above sequence, does the default in the old `Etcd` object created by the user change to `OnDelete`?(From what I understand, this is the expectation). I think it wouldn't change to `OnDelete` unless the user explicitly sets`updateStrategy` to `OnDelete`. Based on my understanding, if we wish for it to change to `OnDelete` after our change in defaults, the field should be a pointer and we should be setting the default during reconciliation during pointer de-referencing (the default parameter in `ptr.Deref`). Please feel free to correct me if I'm wrong.

2026-05-14 06:00 UTC, CaptainIRS commented on docs/proposals/06-sts-ondelete-strategy.md
> +> **Note:** The `controller-revision-hash` is an internal contract of the Kubernetes StatefulSet controller rather than a documented public API. Changes to its semantics are unlikely but possible; if
I don't quite understand the concern here. If Kubernetes changes how the revision hash is calculated, our logic should remain the same, if I'm not wrong? Since we don't rely on the format of the hash or any internal detail and just do string comparisons.

2026-05-14 06:11 UTC, CaptainIRS commented on docs/proposals/07-sts-ondelete-strategy.md
> +**Step 2: Check for non-participating pods that need updating.** If any outdated pod is non-participating, select one for deletion using the following sub-priority:
No, I understand that we don't stick to the classification across reconciliation. My concern is about the fresh classification we do at the start of the reconciliation. Consider this sequence:

Initially there are etcd-0 (F), etcd-1 (F), etcd-2 (L) pods all of which are healthy. Update is triggered.

First reconciliation:
1. OnDelete controller determines all pods are `participating` and `etcd-2` is the leader.
2. Picks `etcd-0` for the update and issues delete call.

Second reconciliation:
1. `etcd-0` hasn't terminated yet. The pod is in `Terminating` and the etcd container is in `Terminated` state. So essentially the pod hasn't been deleted yet.
2. OnDelete determines that `etcd-0` is `non-participating pod that needs updating` according to step-2 (at least that is my understanding, feel free to correct me if I'm wrong).

My concern is whether this classification is correct?

2026-05-14 06:24 UTC, CaptainIRS commented on docs/proposals/06-sts-ondelete-strategy.md
> +The controller determines member roles by reading the member lease's `holderIdentity` field, which contains the member ID and role.
Okay, I checked the source and the etcd controller surprisingly doesn't reconcile for updates to the member lease holderIdentity. So, you're right, checking the member lease is the only way to do it as of now with least delay possible.

2026-05-14 06:27 UTC, CaptainIRS commented on docs/proposals/06-sts-ondelete-strategy.md
> +Delete the selected pod and requeue. Wait for it to come back before proceeding to the next.
I think we can be more explicit in the wording. My understanding was that it would wait for all members to be ready before the requeue, but if it was mentioned explicitly, it would be a lot clear.

2026-05-14 07:22 UTC, CaptainIRS commented on docs/proposals/06-sts-ondelete-strategy.md
> +- The theoretical race condition (an external actor disrupts a pod between the controller's health check and its delete call) is possible but rare in practice, and it exists equally with the current
I think it would be better to reorganize. WDYT?

The first point could be removed and the second point could be modified to include the fact that "if we use Eviction calls, then our eviction call in this scenario would be rejected whereas if we use the Delete call" since I feel it makes it clear about how the `Delete` and `Eviction` approaches are different. Since the second point is actually a limitation compared to the `Eviction` approach, I'd consider moving it to a separate section as this section deals with why `Delete` is the recommended approach (I'm assuming we're just focusing on the pros here).

2026-05-14 07:26 UTC, CaptainIRS commented on docs/proposals/06-sts-ondelete-strategy.md
> +Before deleting the single pod, the controller should trigger an on-demand snapshot (if backup is configured) to ensure that the latest data is persisted. This is because the single-node cluster has
Yes, I'm also in favour of decoupling the ondelete controller from this. The snapshot on presync before update for non-HA could be taken care of as a separate issue. Also, given the member removal DEP (DEP-07), we might change how non-HA updates happen, and thus we might not need a presync snapshot.

2026-05-14 08:02 UTC, ishan16696 approved these changes
Thanks @anveshreddy18 for addressing my review comments. 
LGTM!!

2026-05-14 09:10 UTC, CaptainIRS commented on docs/proposals/07-sts-ondelete-strategy.md
> +1. **Is the pod participating in the etcd quorum?** This is determined by the etcd container's readiness. The readiness probe hits etcd-wrapper's `/readyz` endpoint, which performs an etcd client `Ge
> Learner rejects client reads and writes (client balancer should not route requests to learner)
https://etcd.io/docs/v3.6/learning/design-learner/

It seems like learner wouldn't be able to serve reads. Sorry for the confusion.

2026-05-14 09:12 UTC, CaptainIRS commented on docs/proposals/07-sts-ondelete-strategy.md
> +**Step 2: Check for non-participating pods that need updating.** If any outdated pod is non-participating, select one for deletion using the following sub-priority:
(from offline discussion): It is expected. Though, to avoid the multiple delete calls being sent to pods like this there could be a small check for deletionTimestamp as part of the logic.

2026-05-14 10:02 UTC, anveshreddy18 commented on docs/proposals/06-sts-ondelete-strategy.md
> +The OnDelete controller detects outdated pods by comparing `controller-revision-hash` labels. This hash is computed from the pod template spec only and does not include `volumeClaimTemplates`. This m
From offline discussion with Rinish: Agreed, it's better to remove any dependency between OnDelete & PVC resizing for now and just keeping the reference to how these two relate together is enough for now. I'll be making the changes.

2026-05-14 10:09 UTC, anveshreddy18 commented on docs/proposals/06-sts-ondelete-strategy.md
> +- `etcddruid_ondelete_reconcile_cycles_total`: Number of reconciliation cycles required to complete a full pod update. Labeled by etcd cluster name.
From offline discussion with Rinish: While it's true that we'll lose the in-memory state for these metrics if a druid restart happens in the middle of the update process, but one thing we can do is persist that state in the etcd.status.conditions if we want to continue the counter from what it was previously. This needs further dicussion, will keep it open for now to discuss.

2026-05-14 10:25 UTC, anveshreddy18 commented on docs/proposals/07-sts-ondelete-strategy.md
> +The default is set to `RollingUpdate` to preserve the existing behaviour for current clusters; `OnDelete` is opt-in initially so it can be exercised on selected clusters. Once `OnDelete` has been val
As discussed offline: We'll be having this field as a pointer so that not setting any value means druid can set the updatestrategy to whatever is the default in that specific druid version. I'll add the snippet for go type as well in this to clear the confusion.

2026-05-14 10:38 UTC, anveshreddy18 commented on docs/proposals/06-sts-ondelete-strategy.md
> +> **Note:** The `controller-revision-hash` is an internal contract of the Kubernetes StatefulSet controller rather than a documented public API. Changes to its semantics are unlikely but possible; if
As discussed offline: The confusion stemmed from the understanding that what if kubernetes alters the hash computation mechanism, but what the proposal meant was more about what if the `controller-revision-hash` is not populated in the pod.metadata.labels or if there's a change in how the sts determines if pod's under it are upto date or not, as that contract is not public since the string is part of the label, so it can change in the future - if that happens we might want to change how the ondelete controller determines which pods are upto date and which are outdated. I'll enhance the doc a bit to clear the confusion.

2026-05-14 10:41 UTC, anveshreddy18 commented on docs/proposals/07-sts-ondelete-strategy.md
> +Consider a 3-member etcd cluster with pods `P-0`, `P-1`, and `P-2`. If `P-0` becomes unhealthy (due to network issues, node failure, or an internal error), the cluster still has quorum with `P-1` and
As discussed offline: While your reasoning is correct, k8s restarts of the containers happen if there's a liveness probe which is failing, then kubelet restarts but the etcd container as of now doesn't have it, so we could potentially solve issues by restarting the pod, so in that the original statement is still valid.

2026-05-14 10:42 UTC, anveshreddy18 commented on docs/proposals/06-sts-ondelete-strategy.md
> +Delete the selected pod and requeue. Wait for it to come back before proceeding to the next.
yeah, I'll improve the wording here a bit. Thanks.

2026-05-14 10:43 UTC, anveshreddy18 commented on docs/proposals/06-sts-ondelete-strategy.md
> +- The theoretical race condition (an external actor disrupts a pod between the controller's health check and its delete call) is possible but rare in practice, and it exists equally with the current
Agreed, the first point is generic and second is actually a con, so we can reorganise this block of information for better readability and also expand on the second point as you mentioned.

2026-05-14 10:45 UTC, anveshreddy18 commented on docs/proposals/06-sts-ondelete-strategy.md
> +Before deleting the single pod, the controller should trigger an on-demand snapshot (if backup is configured) to ensure that the latest data is persisted. This is because the single-node cluster has
yeah, I'll raise an issue & PR for that separately to decouple them.

2026-05-14 12:31 UTC, anveshreddy18 commented on docs/proposals/06-sts-ondelete-strategy.md
> +The OnDelete controller detects outdated pods by comparing `controller-revision-hash` labels. This hash is computed from the pod template spec only and does not include `volumeClaimTemplates`. This m
done, pls check :)

2026-05-14 12:31 UTC, anveshreddy18 commented on docs/proposals/06-sts-ondelete-strategy.md
> +The Vertical Pod Autoscaler (VPA) does not modify the StatefulSet spec directly. VPA operates through two independent mechanisms:
done, pls check :)

2026-05-14 12:31 UTC, anveshreddy18 commented on docs/proposals/06-sts-ondelete-strategy.md
> +| Second | etcd process is alive but readiness fails (quorum loss) | Process is healthy. Restarting it gets the new spec without making things worse. |
done, pls check :)

2026-05-14 12:31 UTC, anveshreddy18 commented on docs/proposals/07-sts-ondelete-strategy.md
> +The default is set to `RollingUpdate` to preserve the existing behaviour for current clusters; `OnDelete` is opt-in initially so it can be exercised on selected clusters. Once `OnDelete` has been val
done, pls check :)

2026-05-14 12:31 UTC, anveshreddy18 commented on docs/proposals/06-sts-ondelete-strategy.md
> +> **Note:** The `controller-revision-hash` is an internal contract of the Kubernetes StatefulSet controller rather than a documented public API. Changes to its semantics are unlikely but possible; if
done, pls check :)

2026-05-14 12:33 UTC, anveshreddy18 commented on docs/proposals/06-sts-ondelete-strategy.md
> +Delete the selected pod and requeue. Wait for it to come back before proceeding to the next.
the step 3 in the update procedure covers this now, pls check.

2026-05-14 12:34 UTC, anveshreddy18 commented on docs/proposals/06-sts-ondelete-strategy.md
> +- The theoretical race condition (an external actor disrupts a pod between the controller's health check and its delete call) is possible but rare in practice, and it exists equally with the current
done, pls check :)

2026-05-15 03:18 UTC, CaptainIRS commented on docs/proposals/07-sts-ondelete-strategy.md
> +The default is set to `RollingUpdate` to preserve the existing behaviour for current clusters; `OnDelete` is opt-in initially so it can be exercised on selected clusters. Once `OnDelete` has been val
Looks good, thanks.

2026-05-18 09:42 UTC, anveshreddy18 commented on docs/proposals/07-sts-ondelete-strategy.md
> +**Step 2: Check for non-participating pods that need updating.** If any outdated pod is non-participating, select one for deletion using the following sub-priority:
Can we resolve this as it's an implementation detail and I'll make sure to include this in the code changes?

2026-05-18 09:43 UTC, CaptainIRS commented on docs/proposals/07-sts-ondelete-strategy.md
> +**Step 2: Check for non-participating pods that need updating.** If any outdated pod is non-participating, select one for deletion using the following sub-priority:
Sure, no issues. I'll mark this as resolved, thanks!

2026-05-18 11:18 UTC, anveshreddy18 commented on docs/proposals/07-sts-ondelete-strategy.md
> +   The controller determines local process liveness by inspecting the pod's container status from the Kubernetes API. If the etcd container is in `CrashLoopBackOff`, `Error`, or is not running, the p
I've pushed the changes Rinish.
The `CrashLoopBackOff`, etc are statuses on the container-level itself, but they're not a an API exposed state but they're represented as a `reason` under the `pod.status.containerStatuses[].state.waiting/terminating` state. 

Check these examples:
<img width="584" height="219" alt="image" src="https://github.com/user-attachments/assets/2daaedf9-567d-44a6-ab7f-ccb971150e5a" />
<img width="584" height="219" alt="image" src="https://github.com/user-attachments/assets/3c8a9d5b-1abd-4af2-9121-d33627d2e256" />
<img width="584" height="219" alt="image" src="https://github.com/user-attachments/assets/09ecfc61-f6a9-45d1-82a2-adef9899cc0e" />


So we will look for the container state and the reason to diferentiate between etcd container's being ready:false with quorum loss vs ready:false with container/process issues. I hope that answers your question : pls check the updated proposal.

2026-05-18 11:19 UTC, anveshreddy18 commented on docs/proposals/06-sts-ondelete-strategy.md
> +| First | etcd process is dead (CrashLoopBackOff, Error, not running) | Already broken. Restarting it may fix the issue. |
Addressed, PTAL :)

2026-05-19 04:22 UTC, CaptainIRS commented on docs/proposals/07-sts-ondelete-strategy.md
> +   The controller determines local process liveness by inspecting the pod's container status from the Kubernetes API. If the etcd container is in `CrashLoopBackOff`, `Error`, or is not running, the p
Looks good, thanks for the explanation!

2026-05-19 06:03 UTC, CaptainIRS approved these changes
@anveshreddy18 thanks for addressing the review comments. Just a minor follow-up nit, other than that, LGTM!

2026-05-19 06:03 UTC, CaptainIRS commented on docs/proposals/07-sts-ondelete-strategy.md
> +- This proposal does not cover PVC resizing or volume replacement. The OnDelete strategy makes PVC resizing safer (see [Interaction with PVC Resizing](#interaction-with-pvc-resizing)), but the PVC re
Nit:
```suggestion
- This proposal does not cover PVC resizing or volume replacement.
```
Just a follow-up from https://github.com/gardener/etcd-druid/pull/879#discussion_r3233539561

2026-05-25 11:09 UTC, unmarshall reviewed
1/n reviews

2026-05-25 11:09 UTC, unmarshall commented on docs/proposals/07-sts-ondelete-strategy.md
> +This proposal recommends supporting the `OnDelete` update strategy to be used by etcd-druid to update the StatefulSet pods backing the Etcd cluster members. With `OnDelete`, the Kubernetes StatefulSe
```suggestion
Today, etcd-druid provisions etcd clusters as StatefulSets configured with the RollingUpdate update strategy. On a pod-template change, the StatefulSet controller rolls pods in a fixed highest-to-lowest ordinal order, with no awareness of etcd member health or role. When an existing member is already unhealthy, this ordering can cause an avoidable transient quorum loss during routine spec updates.

This proposal switches etcd-druid to configure the StatefulSet with the `OnDelete` update strategy provided by Kubernetes. Under OnDelete, the StatefulSet controller does not roll pods automatically on pod-template changes; instead, a new dedicated controller in etcd-druid deletes and recreates pods in an order that accounts for member health and cluster role. Voluntary updates — image bumps, configuration changes, resource changes — are then propagated under druid's control, with significantly reduced risk of unintended quorum loss in multi-node clusters.
```

2026-05-25 11:09 UTC, unmarshall commented on docs/proposals/07-sts-ondelete-strategy.md
> +- **Participating pod**: A pod whose etcd container is part of the quorum (the member is either a leader or a follower).
can also be a learner, right?

2026-05-25 11:09 UTC, unmarshall commented on docs/proposals/07-sts-ondelete-strategy.md
> +- **Participating pod**: A pod whose etcd container is part of the quorum (the member is either a leader or a follower).
I see that the two terms introduced `Participating pod` and `Non-participating pod` has been debated.

Perhaps a better phrasing is:
**Participating pod:** A pod whose etcd container is currently serving as a leader or follower in the cluster's quorum (i.e., it passes its readiness probe).
**Non-Participating pod:** A pod whose etcd member is not currently contributing to quorum, regardless of cause (process down, member not yet joined, network-partitioned etc.).

2026-05-25 11:09 UTC, unmarshall commented on docs/proposals/07-sts-ondelete-strategy.md
> +Consider a 3-member etcd cluster with pods `P-0`, `P-1`, and `P-2`. If `P-0` becomes unhealthy (due to network issues, node failure, or an internal error), the cluster still has quorum with `P-1` and
```suggestion
Consider a 3-member cluster with pods P-0, P-1, and P-2. Suppose P-0 is currently unhealthy — it could be partitioned from the network, on a failing node, or hitting an internal etcd error — while P-1 and P-2 are healthy and form a quorum. An operator now triggers a routine spec update, e.g. an image bump. The StatefulSet controller starts at the highest ordinal, deletes P-2, and waits for it to come back ready before proceeding. During that window only P-1 is participating; with 1 of 3 members up, the cluster has lost quorum and stalls writes until P-2 returns. The same outcome repeats when P-1 is rolled next. The unhealthy P-0 — the pod whose deletion would have been safe, since it wasn't contributing anyway — is rolled last, by which time the avoidable downtime has already been incurred.
```

2026-05-25 11:09 UTC, unmarshall commented on docs/proposals/07-sts-ondelete-strategy.md
> +Consider a 3-member etcd cluster with pods `P-0`, `P-1`, and `P-2`. If `P-0` becomes unhealthy (due to network issues, node failure, or an internal error), the cluster still has quorum with `P-1` and
I agree with @CaptainIRS  comment that there are several motivations to introduce `OnDelete` as the chosen strategy to manage StatefulSet pods for an etcd cluster.

* Motivation-1: Reduce the possibility of extended transient quorum loss by intelligently selecting pods to update based on their health.
* Motivation-2: Reduce the number of times the leadership is transferred by selecting the pods based on their current role (follower/learner first and leader last). Of course you cannot handle the situation where the leadership changes mid-update.

2026-05-25 11:09 UTC, unmarshall commented on docs/proposals/07-sts-ondelete-strategy.md
> +The following diagram illustrates how the `RollingUpdate` strategy can lead to quorum loss in this scenario:
The diagram can actually be removed. (1) it is not very clear (2) you have already explained that briefly above so there is no real need to pictorially represent that.

2026-05-25 11:09 UTC, unmarshall commented on docs/proposals/07-sts-ondelete-strategy.md
> +For a single-node etcd cluster, both `RollingUpdate` and `OnDelete` produce the same outcome since there is only one pod to update. The benefit of `OnDelete` is specific to multi-node clusters where
While i agree that we should just use `OnDelete` strategy and not bother switching to `RollingUpdate` for non-HA etcd-clusters, anvesh's response is not correct.

>while what Ishan mentioned is correct that there's no effect but I feel we should respect the user decision on what they want, not obeying it actually makes it more complicated imo.

Which user decision do you hint at? The user has no choice in the matter today w.r.t which update strategy is chosen by etcd-druid internally to manage an etcd cluster. So i am bit confused.

2026-05-25 11:09 UTC, unmarshall commented on docs/proposals/07-sts-ondelete-strategy.md
> +- Introduce a spec field on the Etcd custom resource that allows operators to choose between `RollingUpdate` and `OnDelete` strategies per cluster.
Why should this be done?
This exposes internal implementation detail that etcd-druid uses a StatefulSet behind the scene. If tomorrow for some reason we wish to move away from STS then these strategies might no longer make sense. 

Additionally i would like to understand in which situations would you choose to use `RollingUpdate` and which scenarios would you like to use `OnDelete`. Can you please clarify since you have till this point in the concept not mentioned the use cases for each strategy.

2026-05-25 11:09 UTC, unmarshall commented on docs/proposals/07-sts-ondelete-strategy.md
> +- Ensure that updates triggered by changes to the StatefulSet pod template (image versions, configuration, resource requests) are propagated to pods under druid's control.
not sure how is this a goal? StatefulSet is an internal implementation detail. The user only deals with `Etcd` resource. Kindly explain this goal

2026-05-25 11:09 UTC, unmarshall commented on docs/proposals/07-sts-ondelete-strategy.md
> +- This proposal does not claim to prevent all forms of quorum loss. It reduces the likelihood of quorum loss caused by poorly-ordered voluntary pod updates.
>caused by poorly-ordered voluntary pod updates.

This is an incorrect reason - it is not `poorly ordered` - these usage of words reflects that StatefulSet controller made a bad judgement call. But this is not true, they have clearly defined the update order as part of StatefulSet behavior semantics w.r.t updates and is being clearly documented. It is the poor judgement on our part to depend upon a defined update strategy which can potentially cause transient quorum loss during updates. For nonHA this is fine but for HA it can violate the SLA for availability during updates.

2026-05-25 11:09 UTC, unmarshall commented on docs/proposals/07-sts-ondelete-strategy.md
> +- This proposal does not cover PVC resizing or volume replacement. The OnDelete strategy makes PVC resizing safer (see [Interaction with PVC Resizing](#interaction-with-pvc-resizing)), but the PVC re
Well to do volume resizing, you will have to use `OnDelete` update strategy. So this use case becomes a motivation which you should explicitly mention in the `Motivation` section of this DEP. However detailing on how to achieve volume resizing is out of scope for this DEP and should be covered in a separate DEP.

2026-05-25 11:09 UTC, unmarshall commented on docs/proposals/07-sts-ondelete-strategy.md
> +- Optimizing the update process for clusters with more than 3 replicas (updating multiple pods concurrently while maintaining quorum) is left as future work.
I did not understand this point. An update strategy is for an STS of any size >=1. How can this be a non-goal? When you write a DEP specifically for changing the underline update strategy for HA and non-HA clusters then you envision it in its entirety and then you can say that in iteration-1 of the implementation these will be covered and in iteration-2 of the implementation some other things will be covered. But this cannot be a non-goal for a proposal. You need to think through this.

2026-05-25 11:09 UTC, unmarshall commented on docs/proposals/07-sts-ondelete-strategy.md
> +### Update Strategy as an Etcd Spec Field
As mentioned earlier - please provide reasons to do that.

2026-05-25 11:09 UTC, unmarshall commented on docs/proposals/07-sts-ondelete-strategy.md
> +This is a per-cluster choice. Operators can set different strategies for different Etcd clusters. Changing the field on a live cluster is supported and triggers a seamless transition (see [Transition
There is no transition for an end-user. etcd-druid hides the implementation detail and only provides a high level capability to update an etcd-cluster. This means the user changes the spec, expects that an etcd-cluster will be updated, delegates to etcd-druid which chooses behind the scenes a STS to realize and etcd-cluster (implementation detail) and on top of that chooses a strategy for update (another implementation detail).

In the end for the end-user the end-result is that the target etcd-cluster gets updated or it fails to get updated in which case the status of an `Etcd` resource should reflect that clearly.

2026-05-25 11:09 UTC, unmarshall commented on docs/proposals/07-sts-ondelete-strategy.md
> +A spec field is preferred over a feature gate for this choice because the decision between `RollingUpdate` and `OnDelete` is intended to remain a per-cluster, long-lived setting rather than a global,
why is a feature gate option relevant for comparison? Not clear.

2026-05-25 11:09 UTC, unmarshall commented on docs/proposals/07-sts-ondelete-strategy.md
> +- **Separation of concerns.** The Etcd reconciler ensures the StatefulSet spec matches the desired state among other things; the OnDelete controller propagates that spec to existing pods in a health-
This is not a strong point. etcd reconciler ensures that the you move towards a desired state. Even today you can have errors when calling `Sync` on all managed components. For these errors we requeue. So where is the difference? Updates are intrinsic part of the same reconciler because it defines a new desired state that you need to reconcile to.

2026-05-25 11:09 UTC, unmarshall commented on docs/proposals/07-sts-ondelete-strategy.md
> +- **Pod-by-pod waits do not block the reconciler.** A full update can span many reconciliation cycles, since each pod must come back and rejoin the quorum before the next one is touched. A separate c
This is not a strong argument. In the etcd reconciler we no longer block, we always requeue. So blocking or tie up of threads is not really a concern. If many clusters are getting updated simultaneously then you will just transfer the same issue to the new reconciler.

Also IMHO having 2 reconcilers which are going to reconcile a single `Etcd` resource is not a k8s recommended way as it can lead to race conditions. You can argue that if the rolling update is in progress for an etcd cluster then the main etcd reconciler (that exists today) will skip reconciliation for that Etcd resource and return early. But i do not really get the benefit here. There is the other reconciler that will have to anyways do that work. It is not only STS there are other components like ConfigMap that might also need changes, would you then duplicate the entire set of components for another reconciler?

W.r.t number of threads/workers - for the net new reconciler you will have to also configure that to a non-zero value. So overall the number of workers will have to increase any which way.

2026-05-25 11:09 UTC, unmarshall commented on docs/proposals/07-sts-ondelete-strategy.md
> +The strategy switch itself is coordinated by sequencing: when `spec.updateStrategy` changes on the Etcd CR, the StatefulSet component updates the StatefulSet's `spec.updateStrategy` first, and the On
This is completely unnecessary. It stems from the same observation that exposing this field in the API is pointless from my perspective.

2026-05-25 11:09 UTC, unmarshall commented on docs/proposals/07-quorum-aware-pod-updates.md
> +**Controller predicate:** The controller only reconciles StatefulSets whose `spec.updateStrategy.type` is set to `OnDelete`. This means the controller is always registered in the controller manager b
So for rollingupdates, you will continue to use the existing etcd reconciler and only for on-delete you will delegate to a dedicated controller. This responsibility boundary is not well defined and as stated above is not preferred. I do not understand the need for doing this TBH. Maybe you have strong reasons to suggest that other than the ones that you have mentioned in this doc, but to me the stated reasons are not convincing.

2026-05-25 11:09 UTC, unmarshall commented on docs/proposals/07-sts-ondelete-strategy.md
> +1. **Is the pod participating in the etcd quorum?** This is determined by the etcd container's readiness. The readiness probe hits etcd-wrapper's `/readyz` endpoint, which performs an etcd client `Ge
>it succeeds only when the etcd member can serve traffic, which requires quorum

Not clear. It is possible that the etcd-member can serve traffic but there is no quorum, thus negating this argument. Which should perhaps reword it.

Something like:
```
This is determined by the etcd container's readiness probe, which the kubelet evaluates against the pod's IP directly (the probe does not go through any Service). The probe hits etcd-wrapper's /readyz endpoint, which inside the pod issues a linearizable Get against the local etcd process at 127.0.0.1:<client-port>

A successful probe means: this member is up and in contact with a healthy quorum. 
A failing probe means: either this member is down/partitioned, or the cluster as a whole has lost quorum. The probe alone cannot distinguish those cases — when quorum is lost, every pod's probe fails, including pods whose local etcd process is healthy. The local-process liveness signal in (2) is what lets the controller still pick a useful pod to delete first in that situation.
```

2026-05-25 11:09 UTC, unmarshall commented on docs/proposals/07-sts-ondelete-strategy.md
> +   - **Transient/starting** when `state.Waiting` is set with `ContainerCreating` or `PodInitializing`. These are not classified as dead and the controller leaves them untouched until they progress to
when you say the controller leaves them `untouched` - what does that mean precisely?
Also a container can remain stuck in `ContainerCreating` state right?  Maybe the CSI driver for different reasons fails to attach a PV in which case the container can be stuck in this state till there is manual intervention. But as per your statement (which i might have also misinterpreted) it will leave these pods as `untouched` - this means now the update is stuck as well.

2026-05-25 11:09 UTC, unmarshall commented on docs/proposals/07-sts-ondelete-strategy.md
> +   In the future, adding a liveness probe to the etcd container using etcd's native `/livez` endpoint (available since etcd 3.5.x, performs a serializable/local-only health check) would provide a mor
Above you mentioned:
```
Distinguishing between "process is dead" and "process is alive but quorum is lost" allows the controller to make better decisions about which non-participating pod to update first.
```

But here you say:
```
The OnDelete controller is designed to work without this probe (using container status as described above) and to benefit from it when available.
```

As long as there is a `/livez` endpoint whether you use the one that directly comes from upstream etcd or what is already defined on the container - do you recommend in this DEP to use that or not? A bit unclear.

2026-05-25 11:09 UTC, unmarshall commented on docs/proposals/07-sts-ondelete-strategy.md
> +The controller processes one pod per reconciliation cycle. After updating a pod, it requeues and waits for the pod to come back before proceeding to the next one. This ensures that the cluster is nev
@shreyas-s-rao how are you blocking a reconciler thread? A quick requeue is not a block - it is the opposite of blocking. Can you please explain?

2026-05-25 11:09 UTC, unmarshall commented on docs/proposals/07-sts-ondelete-strategy.md
> +The controller processes one pod per reconciliation cycle. After updating a pod, it requeues and waits for the pod to come back before proceeding to the next one. This ensures that the cluster is nev
It depends - if you have a 5 member cluster and lets say that all members are healthy in the beginning. Then you have a room of 2 to play with without causing loss of quorum. This means if the first pod that you pick to update now gets blocked - should you stop and not proceed further or should you check - `do i have sufficient room to try another Pod without causing quorum to be destroyed` and based on that you either stop or proceed.

I have not thought through this myself but this is a question that i have at the moment. Should we play extremely conservative and stop at the first failure or go to the extent where the quorum is still maintained?

2026-05-25 11:47 UTC, unmarshall requested changes
2/n review comments

2026-05-25 11:47 UTC, unmarshall commented on docs/proposals/07-quorum-aware-pod-updates.md
> +**Step 1: Check if all pods are up to date.** Compare each pod's `controller-revision-hash` with the StatefulSet's `.status.updateRevision`. If all match, the update is complete.
Can you please check if `StatefulSet.Status.UpdatedReplicas` can be used with `OnDelete` update strategy? If we can rely on that then it is going to be cheaper than making a LIST call to get all pods.

https://github.com/kubernetes/kubernetes/issues/73492 - only talks about `CurrentRevision` not getting set. But https://github.com/kubernetes/kubernetes/pull/136833 fixes the issue that was reported in #73492

2026-05-25 11:47 UTC, unmarshall commented on docs/proposals/07-sts-ondelete-strategy.md
> +**Step 2: Check for non-participating pods that need updating.** If any outdated pod is non-participating, select one for deletion using the following sub-priority:
What has been highlighted by @CaptainIRS is valid - you need to record the decision that you took in the previous reconciliation. If a Pod is selected for update and in the next reconciliation you must have a deterministic way to check if there is a `InFlightPod` that has been selected for update in the previous cycle. This should survive the crash of the etcd-druid operator, therefore it should be preserved/captured as part of `Etcd.Status`.

Can you detail out the offline discussions that have happened which marks this as a mere implementation detail?

2026-05-25 11:47 UTC, unmarshall commented on docs/proposals/07-sts-ondelete-strategy.md
> +The controller processes one pod per reconciliation cycle. After updating a pod, it requeues and waits for the pod to come back before proceeding to the next one. This ensures that the cluster is nev
> The controller processes one pod per reconciliation cycle.

Let us consider a case where the quorum is already lost. Out of 3 nodes 2 are unhealthy. Would it make sense to delete both and recreate both together in one shot instead of doing it one at a time at all times?

2026-05-25 11:47 UTC, unmarshall commented on docs/proposals/07-quorum-aware-pod-updates.md
> +**Step 3: Ensure all updated pods are participating.** Before touching any participating pod, verify that every pod already carrying the latest revision is in a participating state. If any updated po
This was precisely my question in one of the comments above. Should we have something similar to `maxUnavailable` but re-interpreted in the context of quorum based workload updates? Of course you will not call this field with this name.

2026-05-25 11:47 UTC, unmarshall commented on docs/proposals/07-quorum-aware-pod-updates.md
> +The controller determines member roles by reading the member lease's `holderIdentity` field, which contains the member ID and role.
There is a potential race condition possible here. Consider the following scenario:
Members: {m-0 (F), m-1 (L), m-2 (F)}
`m-2` has been updated already.

At time T1: leadership change happens and the new leader is `m-0`.
At time T3: member lease reflects this change.
At time T2 (which is > T1 but < T3) etcd-druid selected `m-0` since it was the follower. 

So this will cause yet another leader election because updates to member leases can be delayed.

2026-05-25 11:47 UTC, unmarshall commented on docs/proposals/07-sts-ondelete-strategy.md
> +> **Note:** When the leader pod is deleted with a normal grace period, the etcd server attempts a graceful [leadership transfer](https://github.com/etcd-io/etcd/blob/326d5a2e7765d1d918865d2c3897f0a27
While this is true, you must state clearly that transfer of leadership as done from within the etcd code is `best-effort`. It does not wait for the leadership to be transferred successfully. This helps the reviewer understand what is the trade-off.

2026-05-25 11:47 UTC, unmarshall commented on docs/proposals/07-quorum-aware-pod-updates.md
> +The following diagram summarizes the OnDelete update procedure:
this diagram is not complete and i would remove it.
One example:
`Any non-participating outdates pods?` - in the `yes` branch - next thing is `Is etcd process dead?` - of which pod?

Since you have already explained the flow clearly above i think this diagram is just dead weight and should be removed.

2026-05-25 12:16 UTC, ishan16696 commented
> Introduce DEP-06: Druid controlled pod updates with the help of StatefulSet OnDelete Strategy

Please update the release note as this DEP is `07` not `06`.

2026-05-26 03:04 UTC, unmarshall requested changes

2026-05-26 03:04 UTC, unmarshall commented on docs/proposals/07-quorum-aware-pod-updates.md
> +3. **Eviction with `unhealthyPodEvictionPolicy: AlwaysAllow`**: Allows eviction of all unhealthy pods regardless of budget. Solves the deadlock but weakens PDB protection against external actors (VPA
Just to let you know that in Gardener for etcd cluster `AlwaysAllow` policy is used:
https://github.com/gardener/gardener/blob/c9919c04c9d929df5f17f821086cf41c99810daa/pkg/component/etcd/etcd/bootstrap.go#L765-L778
So this argument that it weakens the PDB protection is not entirely true. Therefore you must understand the reasons why the PDB restriction was relaxed for etcd clusters in gardener so that you can either re-evaluate this point or add additional documentation supporting this point.

2026-05-26 03:04 UTC, unmarshall commented on docs/proposals/07-sts-ondelete-strategy.md
> +The controller uses direct `Delete` calls for all pod deletions, rather than using the eviction API.
you must clarify what `direct Delete` is.

Perhaps you can rephrase it so that there is no room for any doubt/ambiguity/misinterpretation.

```
The controller deletes pods by calling the pod DELETE endpoint (client.Delete), not the `pods/eviction` subresource. The two are distinct API operations: pod DELETE does not consult the `PodDisruptionBudget`, while eviction does. The `OnDelete` controller relies on its own health-aware logic to decide when a delete is safe, so it does not need the PDB's check on top.
```

2026-05-26 03:04 UTC, unmarshall commented on docs/proposals/07-sts-ondelete-strategy.md
> +- The current `RollingUpdate` strategy already uses `Delete` calls internally. Switching to `OnDelete` with `Delete` calls does not change the deletion mechanism, only the ordering.
always provide proof of your claim:

Rephrase:
```
The current RollingUpdate strategy already deletes pods via the pods DELETE endpoint, not the pods/eviction subresource — see
[ref](https://github.com/kubernetes/kubernetes/blob/865560c3d264865c2cf7e86863feb220e7848bba/pkg/controller/statefulset/stateful_pod_control.go#L118-L120)

2026-05-26 03:04 UTC, unmarshall commented on docs/proposals/07-sts-ondelete-strategy.md
> +Transitioning between `RollingUpdate` and `OnDelete` is seamless and requires no manual intervention beyond changing the `spec.updateStrategy` field on the Etcd custom resource.
This is not even required. This entire section IMHO is not required.

2026-05-26 03:04 UTC, unmarshall commented on docs/proposals/07-sts-ondelete-strategy.md
> +- `etcddruid_ondelete_update_duration_seconds`: Time from the first detection of an `updateRevision` change to the completion of all pod updates. Labeled by etcd cluster name.
why should this be specific to ondelete?
There needs to be a single metric to compute the total time it takes to update an etcd cluster. If you really want additional information w.r.t what update strategy was used then have it as a label/tag

2026-05-26 03:04 UTC, unmarshall commented on docs/proposals/07-sts-ondelete-strategy.md
> +- `etcddruid_ondelete_reconcile_cycles_total`: Number of reconciliation cycles required to complete a full pod update. Labeled by etcd cluster name.
Can you please explain how and where will you be using this metric when you have already proposed to capture the total time take to update an etcd cluster?

2026-05-26 03:04 UTC, unmarshall commented on docs/proposals/07-sts-ondelete-strategy.md
> +- **Concurrent pod updates for larger clusters**: For clusters with more than 3 replicas, it is possible to update multiple pods concurrently while maintaining quorum. For example, in a 5-member clus
why is this a future scope and why do we assume that the cluster size is always 3 for a HA etcd cluster?

2026-05-26 05:25 UTC, anveshreddy18 commented on docs/proposals/07-sts-ondelete-strategy.md
> +- **Participating pod**: A pod whose etcd container is part of the quorum (the member is either a leader or a follower).
I've originally added `learner` in the early versions of the proposal but later removed it in favor of the two terms that we've added, as `learner` falls into the `non-participating pod` category because it's not contributing to the quorum and the proposal doesn't talk about it's state. I hope that's fine?

2026-05-26 05:27 UTC, anveshreddy18 commented on docs/proposals/07-sts-ondelete-strategy.md
> +- **Participating pod**: A pod whose etcd container is part of the quorum (the member is either a leader or a follower).
yeah, I can improve the phrasing as you suggested, thanks

2026-05-27 05:16 UTC, anveshreddy18 commented on docs/proposals/07-sts-ondelete-strategy.md
> +For a single-node etcd cluster, both `RollingUpdate` and `OnDelete` produce the same outcome since there is only one pod to update. The benefit of `OnDelete` is specific to multi-node clusters where
I meant that about the API spec field we've proposed to introduce in this DEP where user can specify whether they want to go with quorum preserving way of `OnDelete` or the regular update flow as done by the STS controller with `RollingUpdate`. 

This comment and a few others are actually related to that one decision as to whether we need to allow configuring the updateStrategy or not. I guess we need a discussion on that. Wdyt?

2026-05-27 05:23 UTC, anveshreddy18 commented on docs/proposals/07-sts-ondelete-strategy.md
> +The controller processes one pod per reconciliation cycle. After updating a pod, it requeues and waits for the pod to come back before proceeding to the next one. This ensures that the cluster is nev
Yes, I've also mentioned this in the proposal that with >3 member cluster we have more room to update multiple pods at once and get the update done faster but imo we would still want to be conservative because the permutations and combinations of updates & the kind of issues it'll bring will be a lot and it'll be hard for ondelete controller to dynamically decide what to do next when let say one out of them gets updated but not the other ( gets stuck for some reason ), etc ... The proposal covers all clusters >3 also but makes sure we're not accidentally causing quorum while trying to make the update.

2026-05-27 05:33 UTC, anveshreddy18 commented on docs/proposals/07-sts-ondelete-strategy.md
> +- `etcddruid_ondelete_reconcile_cycles_total`: Number of reconciliation cycles required to complete a full pod update. Labeled by etcd cluster name.
That stemmed from the observation that today we don't have any such metric to count the no.of reconciliation cycles that happened for some action and we mostly assume that a constant `10s` retry or an exponential retry is good but we didn't actually had the data to back that up and say this is the right thing to do... but if we have such a metric ( at least starting with this ondelete controller ) then we would have a way to quantify many cycles does it actually take and associate it with the time from the above metric and come up with the right time/cycle ratio to not requeue too often or too late. I hope this makes sense.

2026-05-29 06:17 UTC, CaptainIRS commented on docs/proposals/07-sts-ondelete-strategy.md
> +- This proposal does not cover PVC resizing or volume replacement. The OnDelete strategy makes PVC resizing safer (see [Interaction with PVC Resizing](#interaction-with-pvc-resizing)), but the PVC re
@unmarshall could you please explain why the `OnDelete` strategy would help in PVC resizing?

As mentioned in the proposal,
> The OnDelete controller's own detection of outdated pods is based on the `controller-revision-hash` label, which is computed from the pod template spec only and does not include `volumeClaimTemplates`. A change to `storageCapacity` or `storageClass` alone will therefore not trigger the OnDelete controller; the PVC resize flow will handle pod replacement through its own mechanism.

So, my understanding is that the logic in the `OnDelete` controller would not come into effect if the StatefulSet spec is updated during PVC resizing. So, it would be the responsibility of the PVC resizing flow to perform the individual pod updates while ensuring there is no transient quorum loss.

2026-05-29 06:35 UTC, CaptainIRS commented on docs/proposals/07-sts-ondelete-strategy.md
> +**Step 2: Check for non-participating pods that need updating.** If any outdated pod is non-participating, select one for deletion using the following sub-priority:
My understanding from the offline discussion is that by doing a fresh classification of the pods at the start of every reconciliation, we could get away without persisting the information about which specific pod we picked for update in the past reconciliations (also holds true across restarts of the etcd-druid itself). The worst thing that could happen is that a pod that is being updated is classified as `non-participating pod that needs updating`, which would result in excessive delete calls issued to the particular pod, but this could be fixed by just checking for the presence of `deletionTimestamp` before issuing a delete call (implementation detail). Maybe @anveshreddy18 can correct me if I'm missing something. Please do let us know if there could be cases where the fresh classification at the start of reconciliation could lead to the wrong pod being picked for update.

2026-05-29 09:53 UTC, anveshreddy18 commented on docs/proposals/07-sts-ondelete-strategy.md
> +- This proposal does not cover PVC resizing or volume replacement. The OnDelete strategy makes PVC resizing safer (see [Interaction with PVC Resizing](#interaction-with-pvc-resizing)), but the PVC re
Thanks for taking time to respond @CaptainIRS, Madhav & Me had a call and we agreed that `OnDelete` is not a requirement but the safest way to go about the PVC resizing...so the original comment is invalid now. I've mentioned in the proposal the same about recommendation vs requirement.

2026-05-29 09:56 UTC, CaptainIRS commented on docs/proposals/07-sts-ondelete-strategy.md
> +- This proposal does not cover PVC resizing or volume replacement. The OnDelete strategy makes PVC resizing safer (see [Interaction with PVC Resizing](#interaction-with-pvc-resizing)), but the PVC re
Not sure I understand this. Do you mean the `controller-revision-hash` actually changes with modifications to `storageCapacity` or `storageClass`?

2026-05-29 09:56 UTC, anveshreddy18 commented on docs/proposals/07-sts-ondelete-strategy.md
> +**Step 2: Check for non-participating pods that need updating.** If any outdated pod is non-participating, select one for deletion using the following sub-priority:
You're right @CaptainIRS , I've also mentioned the same in the call with Madhav and we agreed that we don't need to persist any information in the status as everything is designed to be dynamic by getting all required information from the pods themselves.

2026-05-29 10:01 UTC, anveshreddy18 commented on docs/proposals/07-sts-ondelete-strategy.md
> +- This proposal does not cover PVC resizing or volume replacement. The OnDelete strategy makes PVC resizing safer (see [Interaction with PVC Resizing](#interaction-with-pvc-resizing)), but the PVC re
No, that doesn't change. What I mean is that setting the updateStrategy to `OnDelete` on the STS is a safer way and can be mentioned as such in the proposal that going with OnDelete will also help ease up the PVC resizing flow, not exactly about the involvement of the `ondelete-controller` which we're introducing in this proposal, setting `OnDelete` on the sts & ondelete controller in etcd-druid are two different things essentially and this proposal does both, but the former is helpful for the PVC resizing. Pls lmk if it's still unclear.

2026-05-29 10:20 UTC, anveshreddy18 commented on docs/proposals/07-sts-ondelete-strategy.md
> +Consider a 3-member etcd cluster with pods `P-0`, `P-1`, and `P-2`. If `P-0` becomes unhealthy (due to network issues, node failure, or an internal error), the cluster still has quorum with `P-1` and
Added these two along with the PVC resizing as also a motivation.

2026-05-29 10:21 UTC, anveshreddy18 commented on docs/proposals/07-quorum-aware-pod-updates.md
> +The following diagram illustrates how the `RollingUpdate` strategy can lead to quorum loss in this scenario:
Context: We've decided in the call that we can keep the diagrams as some readers/viewers prefer them and that there's no harm in having them.

2026-05-29 10:23 UTC, anveshreddy18 commented on docs/proposals/07-sts-ondelete-strategy.md
> +- This proposal does not claim to prevent all forms of quorum loss. It reduces the likelihood of quorum loss caused by poorly-ordered voluntary pod updates.
Changed the wording to reflect that sts controller ordering was not suitable for quorum based workloads like etcd instead of the `poorly ordered` word.

2026-05-29 10:30 UTC, anveshreddy18 commented on docs/proposals/07-sts-ondelete-strategy.md
> +This is a per-cluster choice. Operators can set different strategies for different Etcd clusters. Changing the field on a live cluster is supported and triggers a seamless transition (see [Transition
We've discussed this at length in a call and I agree with all the points related to the presence of API field for choosing between strategies - that for the end users it doesn't matter what implementation path we take in the code and the fact that it's very statefulset specific makes it a breaking change if and when we transition out of STS into something like a quorum based workload resource that we might plan to bring in the future.

I've now removed the API field and we're instead going with the feature gate to transition between the update strategies as we start with an alpha gate and eventually making it run with just `OnDelete` in the future once we are fully confident of it.

2026-05-29 10:31 UTC, anveshreddy18 commented on docs/proposals/07-sts-ondelete-strategy.md
> +### Update Strategy as an Etcd Spec Field
Done.
For detailed reply pls check https://github.com/gardener/etcd-druid/pull/879#discussion_r3323729107

2026-05-29 10:32 UTC, anveshreddy18 commented on docs/proposals/07-sts-ondelete-strategy.md
> +- Ensure that updates triggered by changes to the StatefulSet pod template (image versions, configuration, resource requests) are propagated to pods under druid's control.
Done.
For detailed reply, pls check: https://github.com/gardener/etcd-druid/pull/879#discussion_r3323729107

2026-05-29 10:33 UTC, anveshreddy18 commented on docs/proposals/07-sts-ondelete-strategy.md
> +- Introduce a spec field on the Etcd custom resource that allows operators to choose between `RollingUpdate` and `OnDelete` strategies per cluster.
Changed as discussed in the call and as mentioned here: https://github.com/gardener/etcd-druid/pull/879#discussion_r3323729107

2026-05-29 10:34 UTC, anveshreddy18 commented on docs/proposals/07-sts-ondelete-strategy.md
> +A spec field is preferred over a feature gate for this choice because the decision between `RollingUpdate` and `OnDelete` is intended to remain a per-cluster, long-lived setting rather than a global,
This is no longer present as we're going with the feature gate mechanism itself.

2026-05-29 10:37 UTC, anveshreddy18 commented on docs/proposals/07-sts-ondelete-strategy.md
> +- **Separation of concerns.** The Etcd reconciler ensures the StatefulSet spec matches the desired state among other things; the OnDelete controller propagates that spec to existing pods in a health-
As discussed in the call, I've updated the points. Pls check :)

2026-05-29 10:38 UTC, anveshreddy18 commented on docs/proposals/07-sts-ondelete-strategy.md
> +- **Pod-by-pod waits do not block the reconciler.** A full update can span many reconciliation cycles, since each pod must come back and rejoin the quorum before the next one is touched. A separate c
As discussed in the call, I've updated the points. Pls check.

2026-05-29 10:39 UTC, anveshreddy18 commented on docs/proposals/07-sts-ondelete-strategy.md
> +The strategy switch itself is coordinated by sequencing: when `spec.updateStrategy` changes on the Etcd CR, the StatefulSet component updates the StatefulSet's `spec.updateStrategy` first, and the On
I've now removed the API requirement as mentioned in https://github.com/gardener/etcd-druid/pull/879#discussion_r3323729107

2026-05-29 10:41 UTC, anveshreddy18 commented on docs/proposals/07-quorum-aware-pod-updates.md
> +**Controller predicate:** The controller only reconciles StatefulSets whose `spec.updateStrategy.type` is set to `OnDelete`. This means the controller is always registered in the controller manager b
This we discussed that it's fine as etcd reconciler will stay intact and the new ondelete-controller acts in the place of previous sts controller. So the boundary is well defined.

2026-05-29 10:41 UTC, CaptainIRS commented on docs/proposals/07-sts-ondelete-strategy.md
> +- This proposal does not cover PVC resizing or volume replacement. The OnDelete strategy makes PVC resizing safer (see [Interaction with PVC Resizing](#interaction-with-pvc-resizing)), but the PVC re
My point in general is that the PVC resizing flow is independent of the `updateStrategy` of the StatefulSet. The PVC resizing flow will be deleting pods and the StatefulSet controller will be recreating them as the required pod is missing (not because an update was triggered, as the hash doesn't change), so I don't see how the choice of `updateStrategy` matters in this flow.

2026-05-29 10:42 UTC, anveshreddy18 commented on docs/proposals/07-sts-ondelete-strategy.md
> +1. **Is the pod participating in the etcd quorum?** This is determined by the etcd container's readiness. The readiness probe hits etcd-wrapper's `/readyz` endpoint, which performs an etcd client `Ge
> It is possible that the etcd-member can serve traffic but there is no quorum, thus negating this argument
We agreed that's not the case but however I've improved the point to be more detailed as you recommended.

2026-05-29 10:44 UTC, anveshreddy18 commented on docs/proposals/07-sts-ondelete-strategy.md
> +   - **Transient/starting** when `state.Waiting` is set with `ContainerCreating` or `PodInitializing`. These are not classified as dead and the controller leaves them untouched until they progress to
I've now changed the proposal a bit w.r.t to these container statuses, there's a priority order in which we'll delete the non-participating pods based on the container's state prioritising dead -> transient -> alive in that order. Pls check the updated proposal.

2026-05-29 10:46 UTC, anveshreddy18 commented on docs/proposals/07-sts-ondelete-strategy.md
> +   In the future, adding a liveness probe to the etcd container using etcd's native `/livez` endpoint (available since etcd 3.5.x, performs a serializable/local-only health check) would provide a mor
I've now removed all references to the `/livez` endpoint as we're not introducing the endpoint any time soon due to issues it could surface w.r.t prematurely restarting an etcd container, etc.

So we now only use the container statuses to figure out the information related to it's liveness and not depend on any probe. Updated the proposal to reflect the same.

2026-05-29 10:47 UTC, anveshreddy18 commented on docs/proposals/07-quorum-aware-pod-updates.md
> +**Step 1: Check if all pods are up to date.** Compare each pod's `controller-revision-hash` with the StatefulSet's `.status.updateRevision`. If all match, the update is complete.
This was already considered in the proposal as agreed on the call.

2026-05-29 10:50 UTC, anveshreddy18 commented on docs/proposals/07-sts-ondelete-strategy.md
> +The controller processes one pod per reconciliation cycle. After updating a pod, it requeues and waits for the pod to come back before proceeding to the next one. This ensures that the cluster is nev
I did consider that idea initially but if out of those 2 nodes, if at least one of them was only momentarily down leading to transient quorum loss, there's a chance it could come back and join quorum so we want to be conservative with the update process to not cause any artificial quorum loss from our side. So for now it's fine to go one at a time.

2026-05-29 10:52 UTC, anveshreddy18 commented on docs/proposals/07-quorum-aware-pod-updates.md
> +**Step 3: Ensure all updated pods are participating.** Before touching any participating pod, verify that every pod already carrying the latest revision is in a participating state. If any updated po
We agreed that we'll go the conservative route for the initial iteration and if need arises we can improve on that by updating multiple pods at the same time to process the update faster.

2026-05-29 10:57 UTC, anveshreddy18 commented on docs/proposals/07-quorum-aware-pod-updates.md
> +The controller determines member roles by reading the member lease's `holderIdentity` field, which contains the member ID and role.
While this is possible, currently this is our source of truth about the role and if there's delays in updating that, maybe we need to relook at polling it directly from the druid etcd status reconciler instead of relying on info that etcd-backup-restore puts into these leases, but honestly even then a delay is possible depending on the frequency of running the etcd status reconciler. 

And the only downside to this is there is a rare possibility of more leader elections but that cannot be avoided completely, so it's an acceptable limit imo.

Unless we have a hook that updates druid on some endpoint about any change in leadership from the etcd side, it won't be truly accurate - and I didn't find any capability that etcd provides for that right now.

2026-05-29 10:57 UTC, anveshreddy18 commented on docs/proposals/07-sts-ondelete-strategy.md
> +> **Note:** When the leader pod is deleted with a normal grace period, the etcd server attempts a graceful [leadership transfer](https://github.com/etcd-io/etcd/blob/326d5a2e7765d1d918865d2c3897f0a27
Done.

2026-05-29 10:58 UTC, anveshreddy18 commented on docs/proposals/07-quorum-aware-pod-updates.md
> +The following diagram summarizes the OnDelete update procedure:
I've updated the diagram now and as we agreed that we can keep the diagram as some people prefer them over text.

2026-05-29 10:58 UTC, anveshreddy18 commented on docs/proposals/07-sts-ondelete-strategy.md
> +The controller uses direct `Delete` calls for all pod deletions, rather than using the eviction API.
Done.

2026-05-29 10:58 UTC, anveshreddy18 commented on docs/proposals/07-sts-ondelete-strategy.md
> +- The current `RollingUpdate` strategy already uses `Delete` calls internally. Switching to `OnDelete` with `Delete` calls does not change the deletion mechanism, only the ordering.
Done.

2026-05-29 11:00 UTC, anveshreddy18 commented on docs/proposals/07-sts-ondelete-strategy.md
> +Transitioning between `RollingUpdate` and `OnDelete` is seamless and requires no manual intervention beyond changing the `spec.updateStrategy` field on the Etcd custom resource.
That section in it's previous form was deemed not required because of the API spec field but we agreed that we should mention clearly about the flow of transitions that happen while switching between update strategies. I've now updated it.

2026-05-29 11:01 UTC, anveshreddy18 commented on docs/proposals/07-sts-ondelete-strategy.md
> +- `etcddruid_ondelete_update_duration_seconds`: Time from the first detection of an `updateRevision` change to the completion of all pod updates. Labeled by etcd cluster name.
I thought about it and have removed the metrics section entirely for now as I want to introduce them later in a separate issue/PR and to not unnecessarily complicate this DEP. So we can revisit this then. Thanks.

2026-05-29 11:02 UTC, anveshreddy18 commented on docs/proposals/07-sts-ondelete-strategy.md
> +- **Concurrent pod updates for larger clusters**: For clusters with more than 3 replicas, it is possible to update multiple pods concurrently while maintaining quorum. For example, in a 5-member clus
I've now updated it to mean that while we support clusters of all sizes, there's a headroom of updating multiple pods at the same time when the cluster size >3, but that introduces it's own challenges. For the initial iteration, we want to be conservative and go with one at a time for clusters of any size and this can be improved in a later iteration if we see the need for that.

2026-05-29 11:04 UTC, anveshreddy18 commented on docs/proposals/07-sts-ondelete-strategy.md
> +- Optimizing the update process for clusters with more than 3 replicas (updating multiple pods concurrently while maintaining quorum) is left as future work.
I've now changed it as per the recommendations in the call and as highlighted in this comment https://github.com/gardener/etcd-druid/pull/879#discussion_r3323886242. Pls check.

2026-05-29 11:08 UTC, anveshreddy18 commented on docs/proposals/07-sts-ondelete-strategy.md
> +- This proposal does not cover PVC resizing or volume replacement. The OnDelete strategy makes PVC resizing safer (see [Interaction with PVC Resizing](#interaction-with-pvc-resizing)), but the PVC re
> The PVC resizing flow will be deleting pods

This is only possible when the update strategy is set to `OnDelete`, so that way there's a link.

2026-05-29 11:21 UTC, CaptainIRS commented on docs/proposals/07-sts-ondelete-strategy.md
> +- This proposal does not cover PVC resizing or volume replacement. The OnDelete strategy makes PVC resizing safer (see [Interaction with PVC Resizing](#interaction-with-pvc-resizing)), but the PVC re
I'm a bit confused. From what I understand you can delete pods managed by a StatefulSet irrespective of update strategy and the StatefulSet controller will recreate it to match the desired state. Am I missing something?

2026-05-29 11:23 UTC, CaptainIRS commented on docs/proposals/07-sts-ondelete-strategy.md
> +- This proposal does not cover PVC resizing or volume replacement. The OnDelete strategy makes PVC resizing safer (see [Interaction with PVC Resizing](#interaction-with-pvc-resizing)), but the PVC re
From the perspective of the StatefulSet controller there is no update going on. So, it would just treat it as the case where a pod had disappeared and has to be recreated.

2026-05-29 11:32 UTC, anveshreddy18 commented on docs/proposals/07-sts-ondelete-strategy.md
> +- This proposal does not cover PVC resizing or volume replacement. The OnDelete strategy makes PVC resizing safer (see [Interaction with PVC Resizing](#interaction-with-pvc-resizing)), but the PVC re
In general we can always delete the pod and sts will recreate it for us, sure!, but when there's an update and if `RollingUpdate` is set, then we don't have control over the deletion order if we just let STS to do it but if we choose to interfere as well then there's two actors acting on the cluster now ( PVC resizing flow & sts controller), which is also not right imo. So to have a exclusive control over the process to make it safe, `OnDelete` can be a safer way even for PVC resizing.

And no it's not a prerequisite as mentioned in the proposal already. It's just a more controlled way of progressing.

2026-05-29 12:01 UTC, anveshreddy18 commented on docs/proposals/07-quorum-aware-pod-updates.md
> +3. **Eviction with `unhealthyPodEvictionPolicy: AlwaysAllow`**: Allows eviction of all unhealthy pods regardless of budget. Solves the deadlock but weakens PDB protection against external actors (VPA
I don't think that's where we create our PDBs, it happens in etcd-druid itself at https://github.com/gardener/etcd-druid/blob/108ba26b9af71f28d888616d787302971745526b/internal/component/poddistruptionbudget/poddisruptionbudget.go#L109-L124 and we only set `UnhealthyPodEvictionPolicy:AlwaysAllow` if the an annotation is present that explicitly asks for this configuration [here](https://github.com/gardener/etcd-druid/blob/108ba26b9af71f28d888616d787302971745526b/internal/component/poddistruptionbudget/poddisruptionbudget.go#L35-L39)... And currently we only use that for `etcd-events` Etcd resources in g/g as their quorum is not very important compared to the `etcd-main` clusters.

I've also checked a live landscape cluster `etcd-main`'s PDB to confirm and here it is:
<img width="744" height="222" alt="image" src="https://github.com/user-attachments/assets/118c9f63-85b4-4eee-bd69-ff478fa4d11b" />

2026-06-01 10:31 UTC, ishan16696 commented on docs/proposals/07-sts-ondelete-strategy.md
> +This is a per-cluster choice. Operators can set different strategies for different Etcd clusters. Changing the field on a live cluster is supported and triggers a seamless transition (see [Transition
> etcd-druid hides the implementation detail and only provides a high level capability to update an etcd-cluster.

why it has to hide this information ? ... I didn't get it, if statefulset is already exposing the `updateStrategy` api and druid is also simply setting up this sts `updateStrategy`, then why not we let the end user of druid to decide which `updateStrategy` they want to use (defaulting to `OnDelete`), just documents the pros and cons of both strategy.

> when we transition out of STS into something like a quorum based workload resource 

that's hypothetical scenario for now, I don't see it coming in this year or next year, and even if it will come. alot of things need to be revisited, hence I don't buy this argument.

2026-06-04 07:14 UTC, ishan16696 commented on docs/proposals/07-sts-ondelete-strategy.md
> +This is a per-cluster choice. Operators can set different strategies for different Etcd clusters. Changing the field on a live cluster is supported and triggers a seamless transition (see [Transition
I had a offline discussion with @unmarshall , he have answered all of my points
1. To choose the best `updateStrategy` for druid user.
2. If we expose the `updateStrategy` via api and set to `OnDelete` then druid user might think that they have to handle the deletion of etcd member pods, which is wrong.
3. If in futute if upstream statefulset adds one more `updateStrategy` then we will first evaluate it before making it configurable or anything but right now that's not the case.

I'm fine with the answers, so we can go ahead with the `feature-gate`.

2026-06-09 11:40 UTC, unmarshall requested changes
Overall looks good, i have some minor comments

2026-06-09 11:40 UTC, unmarshall commented on docs/proposals/07-sts-ondelete-strategy.md
> +  UpdateStrategyOnDelete: true
Can we give this a more semantically meaningful name like `QuorumAwareUpdates` or something similar? Setting OnDelete as an update strategy is just one of the things that we do. OnDelete controller does candidate selection, pausing when it is not safe to do updates etc. So it is quorum aware.

Similarly the DEP is currently named after STS OnDelete update strategy but that is just one part of the story. So we should perhaps rename the DEP as well.

2026-06-09 11:40 UTC, unmarshall commented on docs/proposals/07-sts-ondelete-strategy.md
> +- **Effect when enabled:** The Etcd reconciler sets `spec.updateStrategy.type = OnDelete` on every managed StatefulSet, and the OnDelete controller (described below) takes over pod updates.
```suggestion
- **Effect when enabled:** The Etcd reconciler sets `spec.updateStrategy.type = OnDelete` on every managed StatefulSet, and the OnDelete controller (described below) orchestrates pod updates.
```

2026-06-09 11:40 UTC, unmarshall commented on docs/proposals/07-quorum-aware-pod-updates.md
> +The controller determines member roles by reading the member lease's `holderIdentity` field, which contains the member ID and role.
do you want to add this as a limitation?

2026-06-09 11:40 UTC, unmarshall commented on docs/proposals/07-sts-ondelete-strategy.md
> +2. **VPA Admission Controller**: When the StatefulSet controller (or the OnDelete controller) recreates a pod, the admission webhook injects VPA-recommended resource values into the new pod's spec at
>When the StatefulSet controller (or the OnDelete controller) recreates a pod,

`OnDelete` controller does not recreate pods, it only deletes it whereas the STS controller does recreate pods. So what you have mentioned is not accurate.

2026-06-10 11:18 UTC, anveshreddy18 commented on docs/proposals/07-sts-ondelete-strategy.md
> +  UpdateStrategyOnDelete: true
Makes sense, I went with a middle ground of both `QuorumAwareUpdatesWithOnDelete` to reflect the actual strategy which helps in making that quorum awareness possible, as otherwise it can be unclear how we're achieving that.

2026-06-11 04:52 UTC, unmarshall approved these changes
Looks good. Thanks for making all the changes to the DEP.

2026-06-11 04:54 UTC, merged